from functools import cached_property
from pathlib import Path

from common.paradox_lib import Game
from PyHelpersForPDXWikis.localsettings import EU5DIR, EU5DIR_DOCUMENTS
try:
    from PyHelpersForPDXWikis.localsettings import EU5_LANGUAGE
except ImportError:
    EU5_LANGUAGE = 'english'


class EuropaUniversalisV(Game):
    """Never construct this object manually. Use the variable eu5game instead.
    This way all data can be cached without having to pass on references to the game or the parser"""
    name = 'Europa Universalis V'
    short_game_name = 'eu5'
    game_path = EU5DIR
    documents_path = EU5DIR_DOCUMENTS
    # launcher_settings = game_path / 'launcher-settings.json'
    wiki_domain = 'eu5.paradoxwikis.com'

    @cached_property
    def parser(self):
        """returns the shared Eu5Parser"""

        # the import has to be inside this method to allow indirect circular dependencies if an entity which is
        # generated by the parser needs to call a method from the parser
        from eu5.parser import Eu5Parser
        return Eu5Parser(language=EU5_LANGUAGE)

    @cached_property
    def cachepath(self) -> Path | None:
        cachepath = super().cachepath
        if cachepath is None:
            return None
        else:
            # to avoid reading cached files which were generated for a different language
            return cachepath / EU5_LANGUAGE

    @cached_property
    def version(self):
        """the branch from caesar_branch.txt. This is not a good indication of a version number, but there isn't a good way to extract one right now"""
        config_path = self.game_path / 'caesar_branch.txt'
        with open(config_path, 'r') as config_file:
            return config_file.read().removeprefix('release/')

    @cached_property
    def full_version(self):
        """the build revision from caesar_rev.txt"""
        config_path = self.game_path / 'caesar_rev.txt'
        with open(config_path, 'r') as config_file:
            return self.version + '-' + config_file.read()


eu5game = EuropaUniversalisV()