from functools import cached_property
from operator import attrgetter

import sys

from eu5.eu5_file_generator import Eu5FileGenerator
from eu5.eu5lib import GoodCategory, Eu5GameConcept, Price
from eu5.text_formatter import Eu5WikiTextFormatter


class TableGenerator(Eu5FileGenerator):

    @cached_property
    def formatter(self) -> Eu5WikiTextFormatter:
        return self.parser.formatter

    def localize(self, key: str, default: str = None) -> str:
        return self.parser.localize(key, default)

    def format_modifier_section(self, section: str, entity):
        if hasattr(entity, section):
            return self.create_wiki_list([modifier.format_for_wiki() for modifier in getattr(entity, section)])
        else:
            return ''

    def generate_building_tables(self):
        sorted_buildings = sorted(
            self.parser.buildings.values(),
            #[good for good in self.parser.goods.values() if good.category == category and good.method == method]
            key=attrgetter('display_name')
            )
        buildings = [{
            'Name': f'{{{{iconbox|{building.display_name}|{building.description}|w=300px|image={building.get_wiki_filename()}}}}}',
            'Time': building.build_time,
            'Price': building.price.format() if isinstance(building.price, Price) else building.price,
            'Destroy Price': building.destroy_price.format() if building.destroy_price else '',
            'category': building.category,
            'foreign':  building.is_foreign,
            'Pop': building.pop_type,
            'employment_size': building.employment_size,
            'Town': building.town,
            'City': building.city,
            'Max levels': building.max_levels,
            'Modifiers': self.format_modifier_section('modifier', building),
            'Modifiers if in capital': self.format_modifier_section('capital_modifier', building),
            'Country modifiers if in capital': self.format_modifier_section('capital_country_modifier', building),

        } for building in sorted_buildings]
        return self.make_wiki_table(buildings, table_classes=['mildtable', 'plainlist'],
                                     one_line_per_cell=True,
                                     remove_empty_columns=True,
                                     )

    def generate_concept_tables(self):
        concepts = sorted(self.parser.game_concepts.values(), key=attrgetter('family', 'display_name'))
        result = []
        family = None
        all_concept_names = list(self.parser.game_concepts.keys()) + [concept.display_name for concept in concepts]
        for concept in concepts:
            if concept.is_alias:
                continue
            if concept.family != family:
                family = concept.family
                result.append(f'== {family if family else "Uncategorized"} ==')
            result.extend(self.get_concept_section(all_concept_names, concept))
        return result

    def get_concept_section(self, all_concept_names, concept: Eu5GameConcept):
        result = [f'=== {concept} ===']
        if concept.alias:
            alias_display_names = [alias.display_name for alias in concept.alias]
            result.append(
                f'{{{{hatnote|Aliases: {", ".join(self.formatter.format_localization_text(alias_display_name, all_concept_names) for alias_display_name in alias_display_names)}}}}}{{{{anchor|{"}}{{anchor|".join(alias_display_names)}}}}}')
        result.append(f'<section begin=autogenerated_concept_{concept.name}/>')
        result.append(self.get_concept_section_contents(all_concept_names, concept))
        result.append(f'<section end=autogenerated_concept_{concept.name}/>')
        return result

    def get_concept_section_contents(self, all_concept_names, concept):
        return self.formatter.format_localization_text(concept.description, all_concept_names)

    def generate_goods_tables(self):
        result = []
        for section, table in self.get_goods_tables().items():
            result.append(f'=== {section} ===')
            result.append(self.surround_with_autogenerated_section(section, table, add_version_header=True))
        return result

    def get_goods_tables(self):
        result = {}
        for category in GoodCategory:
            methods = set(good.method for good in self.parser.goods.values() if good.category == category)
            for method in sorted(methods):
                result[f'{category}_{method if method else "default"}'] = self.get_goods_table(category, method)
        return result

    def get_goods_table(self, category: GoodCategory, method: str):
        sorted_goods = sorted([good for good in self.parser.goods.values() if good.category == category and good.method == method], key=attrgetter('display_name'))
        goods = [{
            'Name': f'{{{{iconbox|{good.display_name}|{good.description}|w=300px|image={good.get_wiki_filename()}}}}}',
            'Base production': good.base_production,
            'Default price': good.default_market_price,
            'Inflation': 'yes' if good.inflation else '',
            'Transport cost': good.transport_cost,

        } for good in sorted_goods]
        return self.make_wiki_table(goods, table_classes=['mildtable', 'plainlist'],
                                     one_line_per_cell=True,
                                     remove_empty_columns=True,
                                     )


if __name__ == '__main__':
    TableGenerator().run(sys.argv)