from functools import cached_property
from operator import attrgetter

from eu5.eu5_file_generator import Eu5FileGenerator
from eu5.eu5lib import GoodCategory
from eu5.text_formatter import Eu5WikiTextFormatter


class TableGenerator(Eu5FileGenerator):

    @cached_property
    def formatter(self) -> Eu5WikiTextFormatter:
        return self.parser.formatter

    def localize(self, key: str, default: str = None) -> str:
        return self.parser.localize(key, default)

    def generate_concept_tables(self):
        concepts = sorted(self.parser.game_concepts.values(), key=attrgetter('family', 'display_name'))
        result = []
        family = None
        all_concept_names = list(self.parser.game_concepts.keys()) + [concept.display_name for concept in concepts]
        for concept in concepts:
            if concept.is_alias:
                continue
            if concept.family != family:
                family = concept.family
                result.append(f'== {family if family else "Uncategorized"} ==')
            result.append(f'=== {concept} ===')
            if concept.alias:
                alias_display_names = [alias.display_name for alias in concept.alias]
                result.append(f'{{{{hatnote|Aliases: {", ".join(self.formatter.format_localization_text(alias_display_name, all_concept_names) for alias_display_name in alias_display_names)}}}}}{{{{anchor|{"}}{{anchor|".join(alias_display_names)}}}}}')

            result.append(f'<section begin=autogenerated_concept_{concept.name} />')
            result.append(self.formatter.format_localization_text(concept.description, all_concept_names))
            result.append(f'<section end=autogenerated_concept_{concept.name} />')
        return result

    def generate_goods_tables(self):
        result = []
        for category in GoodCategory:
            result.append(f'== {category.display_name} ==')
            methods = set(good.method for good in self.parser.goods.values() if good.category == category)
            for method in sorted(methods):
                if len(method) > 1:
                    result.append(f'=== {self.parser.localize(method)} ===')
                result.append(self.surround_with_autogenerated_section(f'{category}_{method if method else "default"}', self.get_goods_table(category, method), add_version_header=True))
        return result

    def get_goods_table(self, category: GoodCategory, method: str):
        sorted_goods = sorted([good for good in self.parser.goods.values() if good.category == category and good.method == method], key=attrgetter('display_name'))
        goods = [{
            'Name': f'{{{{iconbox|{good.display_name}|{good.description}|w=300px}}}}',
            'Base production': good.base_production,
            'Default price': good.default_market_price,
            'Inflation': 'yes' if good.inflation else '',
            'Transport cost': good.transport_cost,

        } for good in sorted_goods]
        return self.make_wiki_table(goods, table_classes=['mildtable', 'plainlist'],
                                     one_line_per_cell=True,
                                     remove_empty_columns=True,
                                     )
