from collections.abc import Iterable

from operator import attrgetter

import sys

from common.paradox_lib import unsorted_groupby
from common.paradox_parser import Tree
from eu5.eu5_file_generator import Eu5FileGenerator
from eu5.eu5lib import GoodCategory, Eu5GameConcept, Building, Law, LawPolicy, Good, EstatePrivilege, Advance
from eu5.parser import Eu5Parser


class TableGenerator(Eu5FileGenerator):

    def merge_multiple_sections(self, headers_with_content: dict[str, str]|list[tuple[str, str]]):
        result = []
        if isinstance(headers_with_content, dict):
            headers_with_content = [(header, content) for header, content in headers_with_content.items()]
        for header, content in headers_with_content:
            if content.strip() == '':
                continue
            section = []
            if header:
                section.append(f"'''{header}:'''")
            section.append(content)
            result.append('\n'.join(section))
        return '\n'.join(result)

    def format_pms(self, building):
        pm_lists = building.unique_production_methods.copy()
        if building.possible_production_methods:
            pm_lists.append(building.possible_production_methods)
        formatted_pm_categories = []
        for pm_list in pm_lists:
            formatted_pms = []
            for pm in pm_list:
                formatted_pms.extend(pm.format(icon_only=True))
            formatted_pm_categories.append(self.create_wiki_list(formatted_pms))
        return '\n----\n'.join(formatted_pm_categories)

    def generate_building_tables(self):
        result = []
        previous_type = None
        for (type_name, category), table in self.get_building_tables().items():
            if type_name != previous_type:
                result.append(f'== {type_name} buildings ==')
                previous_type = type_name
            result.append(f'=== {category.display_name} ===')

            section_content = f'{{{{iconbox||{category.description}|image={category.get_wiki_filename()}}}}}' + '\n' + table
            result.append(self.surround_with_autogenerated_section(f'buildings_{type_name.replace("+", "_")}_{category.name}', section_content, add_version_header=True))
        return result

    def get_building_sections(self):
        return {
            f'buildings_{type_name.replace("+", "_")}_{category.name}': f'{{{{iconbox||{category.description}|image={category.get_wiki_filename()}}}}}' + '\n' + table
            for (type_name, category), table in self.get_building_tables().items()
        }

    def get_building_tables(self):
        results = {}
        type_names = {(True, True, True): 'common',
                          (False, False, True): 'rural',
                          (False, True, False): 'town',
                          (True, False, False): 'city',
                          (True, True, False): 'town+city',
                          (False, True, True): 'town+rural',
                          (True, False, True): 'city+rural',
                          (False, False, False): 'nowhere',
                          }
        buildings_by_location_type = {type_names[typ]: list(buildings) for typ, buildings in unsorted_groupby(self.parser.buildings.values(), key=attrgetter('city', 'town', 'rural_settlement'))}
        for type_name, buildings_for_type in buildings_by_location_type.items():
            buildings_by_category = unsorted_groupby(buildings_for_type, key=attrgetter('category'))
            for category, buildings in buildings_by_category:
                sorted_buildings = sorted(buildings, key=attrgetter('display_name'))
                results[(type_name, category)] = self.get_building_table(sorted_buildings)
        return results

    def get_building_table(self, sorted_buildings: list[Building]):
        # sorted_buildings = [b for b in sorted_buildings if b.possible_production_methods and not isinstance(b.possible_production_methods[0], ProductionMethod)]
        # sorted_buildings = [self.parser.buildings['jewelry_guild']] + sorted_buildings[:20]
        buildings = [{
            # 'Name': f'{{{{iconbox|{building.display_name}|{building.description}|w=300px|image={building.get_wiki_filename()}}}}}',
            # 'Time': building.build_time,
            # 'Price': building.price.format() if isinstance(building.price, Price) else building.price,
            # 'Destroy Price': building.destroy_price.format() if building.destroy_price else '',
            # 'Construction demand': building.construction_demand.format(icon_only=True) if hasattr(building.construction_demand, 'format') else building.construction_demand,
            # 'category': building.category,
            # 'foreign':  building.is_foreign,
            # 'Pop': building.pop_type,
            # 'Employees': round(building.employment_size),
            # 'Town': building.town,
            # 'City': building.city,
            # 'Max levels': building.max_levels,
            # 'Modifiers': self.format_modifier_section('modifier', building),
            # 'Modifiers if in capital': self.format_modifier_section('capital_modifier', building),
            # 'Country modifiers if in capital': self.format_modifier_section('capital_country_modifier', building),
            'Name': f'{{{{iconbox|{building.display_name}|{building.description}|w=300px|desc_class=hidem|image={building.get_wiki_filename()}}}}}',
'Modifier': self.format_modifier_section('modifier', building),  # modifier: list[eu5.eu5lib.Eu5Modifier]
'Requirements': self.merge_multiple_sections([
    ('Location', self.formatter.format_trigger(building.location_potential) + self.formatter.format_trigger(building.allow)),
    ('Country', self.formatter.format_trigger(building.country_potential)),
    ('To destroy', self.formatter.format_trigger(building.can_destroy)),
    ('To keep', self.formatter.format_trigger(building.remove_if))
]),
# 'Country Potential': self.formatter.format_trigger(building.country_potential),  # country_potential: <class 'eu5.eu5lib.Trigger'>
# 'Location Potential': self.formatter.format_trigger(building.location_potential),  # location_potential: <class 'eu5.eu5lib.Trigger'>
# 'Allow': self.formatter.format_trigger(building.allow),  # allow: <class 'eu5.eu5lib.Trigger'>
# 'Can Destroy': self.formatter.format_trigger(building.can_destroy),  # can_destroy: <class 'eu5.eu5lib.Trigger'>
# 'Remove If': self.formatter.format_trigger(building.remove_if),  # remove_if: <class 'eu5.eu5lib.Trigger'>

'Build Time': building.build_time,  # build_time: <class 'int'>
'Modifiers': self.merge_multiple_sections([
    # 'Capital Country Modifier': self.format_modifier_section('capital_country_modifier', building),  # capital_country_modifier: list[eu5.eu5lib.Eu5Modifier]
    ('Country (if in Capital)', self.format_modifier_section('capital_country_modifier', building)),  # capital_country_modifier: list[eu5.eu5lib.Eu5Modifier]
# 'Capital Modifier': self.format_modifier_section('capital_modifier', building),  # capital_modifier: list[eu5.eu5lib.Eu5Modifier]
    ('Location (if in Capital)', self.format_modifier_section('capital_modifier', building)),
# 'Market Center Modifier': self.format_modifier_section('market_center_modifier', building),  # market_center_modifier: list[eu5.eu5lib.Eu5Modifier]
    ('Location (if in Market Center)', self.format_modifier_section('market_center_modifier', building)),
# 'Foreign Country Modifier': self.format_modifier_section('foreign_country_modifier', building),  # foreign_country_modifier: list[eu5.eu5lib.Eu5Modifier]
    ('Building owner', self.format_modifier_section('foreign_country_modifier', building)),
    # 'Raw Modifier': self.format_modifier_section('raw_modifier', building),  # raw_modifier: list[eu5.eu5lib.Eu5Modifier]
    ('Raw Modifier', self.format_modifier_section('raw_modifier', building)),
]),
# 'Category': building.category,  # category: <class 'str'>
# 'City': '[[File:Yes.png|20px|City]]' if building.city else '[[File:No.png|20px|Not City]]',  # city: <class 'bool'>
'Construction Demand': building.construction_demand.format(icon_only=True) if hasattr(building.construction_demand, 'format') else building.construction_demand,  # construction_demand: <class 'eu5.eu5lib.GoodsDemand'>
'Destroy Price': building.destroy_price.format(icon_only=True) if hasattr(building.destroy_price, 'format') else building.destroy_price,  # destroy_price: <class 'eu5.eu5lib.Price'>
'Employment': f'{building.employment_size:g} {building.pop_type.get_wiki_icon()}',  # employment_size: <class 'float'>
'Estate': building.estate.get_wiki_link_with_icon() if building.estate else '',
# 'Graphical Tags': self.create_wiki_list([graphical_tags for graphical_tags in building.graphical_tags]),  # graphical_tags: list[str]
'Max Levels': building.max_levels,  # max_levels: int | str
'Obsolete': self.create_wiki_list([obsolete.get_wiki_link_with_icon() if obsolete else '' for obsolete in building.obsolete]),  # obsolete: list[eu5.eu5lib.Building]
# 'On Built': self.formatter.format_effect(building.on_built),  # on_built: <class 'eu5.eu5lib.Effect'>
# 'On Destroyed': self.formatter.format_effect(building.on_destroyed),  # on_destroyed: <class 'eu5.eu5lib.Effect'>
'Production Methods': self.format_pms(building),  # possible_production_methods: list[eu5.eu5lib.ProductionMethod]
# 'Possible Production Methods': self.create_wiki_list([possible_production_methods.format(icon_only=True) if hasattr(possible_production_methods, 'format') else possible_production_methods for possible_production_methods in building.possible_production_methods]),  # possible_production_methods: list[eu5.eu5lib.ProductionMethod]
# 'Unique Production Methods': self.create_wiki_list([unique_production_methods.format(icon_only=True) if hasattr(unique_production_methods, 'format') else unique_production_methods for unique_production_methods in building.unique_production_methods]),  # unique_production_methods: list[eu5.eu5lib.ProductionMethod]
'Price': building.price.format(icon_only=True) if hasattr(building.price, 'format') else building.price,  # price: <class 'eu5.eu5lib.Price'>


# 'Rural Settlement': '[[File:Yes.png|20px|Rural Settlement]]' if building.rural_settlement else '[[File:No.png|20px|Not Rural Settlement]]',  # rural_settlement: <class 'bool'>
# 'Town': '[[File:Yes.png|20px|Town]]' if building.town else '[[File:No.png|20px|Not Town]]',  # town: <class 'bool'>
        'Notes': self.get_building_notes(building),
        } for building in sorted_buildings]
        return self.make_wiki_table(buildings, table_classes=['mildtable', 'plainlist'],
                                     one_line_per_cell=True,
                                     remove_empty_columns=True,
                                     )


    def generate_concept_tables(self):
        concepts = sorted(self.parser.game_concepts.values(), key=attrgetter('family', 'display_name'))
        result = []
        family = None
        all_concept_names = list(self.parser.game_concepts.keys()) + [concept.display_name for concept in concepts]
        for concept in concepts:
            if concept.is_alias:
                continue
            if concept.family != family:
                family = concept.family
                result.append(f'== {family if family else "Uncategorized"} ==')
            result.extend(self.get_concept_section(all_concept_names, concept))
        return result

    def get_concept_section(self, all_concept_names, concept: Eu5GameConcept):
        result = [f'=== {concept} ===']
        if concept.alias:
            alias_display_names = [alias.display_name for alias in concept.alias]
            result.append(
                f'{{{{hatnote|Aliases: {", ".join(self.formatter.format_localization_text(alias_display_name, all_concept_names) for alias_display_name in alias_display_names)}}}}}{{{{anchor|{"}}{{anchor|".join(alias_display_names)}}}}}')
        result.append(f'<section begin=autogenerated_concept_{concept.name}/>{self.get_concept_section_contents(all_concept_names, concept)}<section end=autogenerated_concept_{concept.name}/>')
        return result

    def get_concept_section_contents(self, all_concept_names, concept):
        return self.formatter.format_localization_text(concept.description, all_concept_names)

    def generate_concept_tables_russian(self):
        concepts = sorted(self.parser.game_concepts.values(), key=attrgetter('family', 'display_name'))
        ru_parser = Eu5Parser(language='russian')
        result = []
        family = None
        all_concept_names = list(self.parser.game_concepts.keys()) + [concept.display_name for concept in concepts] + [concept.display_name for concept in ru_parser.game_concepts.values()]
        table_data = []
        for concept in concepts:
            if concept.is_alias:
                continue
            ru_concept = ru_parser.game_concepts[concept.name]
            if concept.family != family:
                if table_data:
                    result.append(self.make_wiki_table(table_data, table_classes=['mildtable', 'plainlist'],
                                                       one_line_per_cell=True,
                                                       remove_empty_columns=True,
                                                       ))
                    table_data = []
                family = concept.family
                result.append(f'== {family if family else "Uncategorized"} ==')
            table_data.append(self.get_concept_section_russian(all_concept_names, concept, ru_concept, ru_parser))
        result.append(self.make_wiki_table(table_data, table_classes=['mildtable', 'plainlist'],
                                           one_line_per_cell=True,
                                           remove_empty_columns=True,
                                           ))
        return result

    def get_concept_section_russian(self, all_concept_names, concept: Eu5GameConcept, ru_concept: Eu5GameConcept, ru_parser: Eu5Parser):
        result = [f'=== {concept} ===']

        if concept.alias:
            alias_display_names = [alias.display_name for alias in concept.alias]
            ru_alias_display_names = [alias.display_name for alias in ru_concept.alias]
            aliases = f'{", ".join(self.formatter.format_localization_text(alias_display_name, all_concept_names) for alias_display_name in alias_display_names)}{{{{anchor|{"}}{{anchor|".join(alias_display_names)}}}}}'
            ru_aliases = f'{", ".join(self.formatter.format_localization_text(alias_display_name, all_concept_names) for alias_display_name in ru_alias_display_names)}{{{{anchor|{"}}{{anchor|".join(ru_alias_display_names)}}}}}'
        else:
            aliases = ''
            ru_aliases = ''

        return {
            'Concept': concept.display_name,
            'Aliases': aliases,
            'Text': self.get_concept_section_contents(all_concept_names, concept),
            'RU Concept': ru_concept.display_name,
            'RU Aliases': ru_aliases,
            'RU Text': f'<section begin=autogenerated_concept_{concept.name}/>{self.get_concept_section_contents(all_concept_names, ru_concept)}<section end=autogenerated_concept_{concept.name}/>',
        }



    def generate_estate_privileges_table(self):
        result = []
        for sectionname, section in self.get_privileges_sections().items():
            estate = sectionname.removeprefix('estate_privileges_')
            result.append(f'=== {self.parser.estates[estate].display_name} privileges ===')
            result.append(self.surround_with_autogenerated_section(sectionname, section, add_version_header=True))
        return result

    def get_privileges_sections(self):
        sections = {}
        for estate, privileges in unsorted_groupby(self.parser.estate_privileges.values(), key=attrgetter('estate')):
            privileges = sorted(privileges, key=attrgetter('display_name'))
            sections[f'estate_privileges_{estate.name}'] = self.get_privileges_table(privileges)
        return sections

    def get_privileges_table(self, privileges: list[EstatePrivilege]):
        privilege_table_data = [{
            'Name': f'{{{{iconbox|{privilege.display_name}|{privilege.description}|w=300px|image={privilege.get_wiki_filename()}}}}}',
            # 'Estate': privilege.estate.get_wiki_link_with_icon() if privilege.estate else '',
            'Requirements': self.merge_multiple_sections([
                ('', self.formatter.format_trigger(privilege.potential)),
                ('', self.formatter.format_trigger(privilege.allow)),
                ('Can Revoke', self.formatter.format_trigger(privilege.can_revoke)),
            ]),
            'On Fully Activated': self.formatter.format_effect(privilege.on_fully_activated),
            'Effects': self.merge_multiple_sections([
                ('', self.format_modifier_section('country_modifier', privilege)),
                ('On Activate', self.formatter.format_effect(privilege.on_activate)),
                ('On Deactivate', self.formatter.format_effect(privilege.on_deactivate)),
                ('Location Modifier', self.format_modifier_section('location_modifier', privilege)),
                ('Province Modifier', self.format_modifier_section('province_modifier', privilege)),
            ])
        } for privilege in privileges]
        return self.make_wiki_table(privilege_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )

    def generate_goods_tables(self):
        result = []
        for section, table in self.get_goods_tables().items():
            if not table:
                continue
            if section.endswith('_food'):
                result.append(f'==== Food ====')
            else:
                result.append(f'=== {self.localize(section).title()} ===')

            result.append(self.surround_with_autogenerated_section(section, table, add_version_header=True))
        return result

    def get_goods_tables(self):
        result = {}
        for category in GoodCategory:
            goods_in_category = [good for good in self.parser.goods.values() if good.category == category]
            special_goods = []
            if category == GoodCategory.produced:
                goods_in_category_without_method = []
                for good in goods_in_category:
                    special_goods.append(good) if good.method else goods_in_category_without_method.append(good)
                goods_in_category = goods_in_category_without_method
            result[f'{category}'] = self.get_goods_table([good for good in goods_in_category if good.food == 0])
            result[f'{category}_food'] = self.get_goods_table([good for good in goods_in_category if good.food > 0])
            result[f'{category}_special'] = self.get_goods_table(special_goods)

        return result

    def _get_goods_iconbox(self, good) -> str:
        lightness = good.color.rgb_r + good.color.rgb_g + good.color.rgb_b
        if lightness > 2:
            shadow = 'text-shadow:1px 1px 3px #000000'
        else:
            shadow = 'text-shadow:1px 1px 3px'
        shadow = f';{shadow}'
        return f'{{{{iconbox|{good.display_name}|{good.description}|w=300px|desc_class=hidem|image={good.get_wiki_filename()}|color={good.color.css_color_string}{shadow}}}}}'

    def get_goods_table(self, goods: Iterable[Good]):
        sorted_goods = sorted(goods, key=attrgetter('display_name'))

        if not sorted_goods:
            return ''
        goods = []
        for good in sorted_goods:
            row = {
                'rowspan="2" | Name': self._get_goods_iconbox(good),
                'rowspan="2" | Base production': good.base_production,
                'rowspan="2" | Default price': good.default_market_price,
                'rowspan="2" | Food': good.food,
                'rowspan="2" | RGO type': self.localize(good.method),
                'rowspan="2" | Inflation': 'yes' if good.inflation else '',
                'rowspan="2" | Transport cost': good.transport_cost,
            }
            for pop in self.parser.pop_types.values():
                row[pop.get_wiki_icon()] = self.formatter.format_float(good.demands[pop]) if good.demands[pop] != 0 else 0
            goods.append(row)
        table = self.make_wiki_table(goods, table_classes=['mildtable', 'plainlist'],
                                     one_line_per_cell=True,
                                     remove_empty_columns=True,
                                     )
        table = table.replace('!! [[File:', f'''!! colspan="{len(self.parser.pop_types)}" | Pop demands
|-
! [[File:''', 1)
        return table
    def generate_goods_tags_lists(self):
        tags = {tag for good in self.parser.goods.values() for tag in good.custom_tags}
        result = []
        for tag in sorted(tags):
            result.append(self.surround_with_autogenerated_section(f'goods_list_{tag}', self.get_goods_tag_list(tag)))

        return result

    def get_goods_tag_list(self, tag: str):
        return self.create_wiki_list([good.get_wiki_link_with_icon() for good in sorted(self.parser.goods.values(), key=attrgetter('display_name')) if tag in good.custom_tags])

    def generate_law_tables_international_organizations(self):
        result = []
        for (io_type_loc, io_type), laws in unsorted_groupby(
                [law for law in self.parser.laws.values() if law.io_type],
                key=lambda law: (
                        self.parser.international_organizations[law.io_type].display_name
                        if law.io_type in self.parser.international_organizations
                        else law.io_type.title(),
                        law.io_type,
                )):
            result.append(f'== {io_type_loc} ==')

            for (law_category_loc, law_category), laws_in_category in unsorted_groupby(
                    laws,
                    key=lambda law: (
                            law.law_category_loc,
                            law.law_category
                    )):
                if not law_category:
                    law_category_loc = 'uncategorized'
                result.append(f'=== {law_category_loc} ===')
                result.append(
                    self.surround_with_autogenerated_section(
                        self._get_law_section_name(io_type, law_category),
                        self.get_laws_as_sections(laws_in_category, 4),
                        add_version_header=True
                    )
                )

        return result

    def generate_law_tables(self):
        result = {}
        for (law_category_loc, law_category), laws_in_category in unsorted_groupby(
                [law for law in self.parser.laws.values() if not law.io_type],
                key=lambda law: (
                        law.law_category_loc,
                        law.law_category
                )):
            if law_category:
                filename_suffix = law_category
            else:
                filename_suffix = 'uncategorized'
            result[filename_suffix] = self.surround_with_autogenerated_section(self._get_law_section_name('', law_category),  self.get_laws_as_sections(laws_in_category, 3), add_version_header=True)
        return result

    def get_law_tables(self, section_level: int = None):
        result = {}
        for (io_type, law_category), laws in unsorted_groupby(self.parser.laws.values(), key=attrgetter('io_type', 'law_category')):
            if section_level is None:
                data = self.get_law_table(laws)
            else:
                if io_type == '':
                    increased_section_level = 0
                else:
                    increased_section_level = 1
                data =  self.get_laws_as_sections(laws, section_level + increased_section_level)
            result[self._get_law_section_name(io_type, law_category)] = data

        return result

    def _get_law_section_name(self, io_type, law_category) -> str:
        if not law_category:
            law_category = 'uncategorized'
        if io_type == '':
            io_type_section = ''
        else:
            io_type_section = f'io_{io_type}_'
        section_name = f'laws_{io_type_section}{law_category}'
        return section_name

    def get_law_table(self, laws: Iterable[Law]):
        law_data = [self.get_law_data(law) for law in laws]
        return self.make_wiki_table(law_data, table_classes=['mildtable', 'plainlist'],
                                    one_line_per_cell=True,
                                    remove_empty_columns=True,
                                    )

    def get_law_data(self, law: Law) -> dict[str, str]:
        return {
            'Name': f'{{{{iconbox|{law.display_name}|{law.description}|w=300px|image={law.get_wiki_filename()}}}}}',
            'Potential': self.formatter.format_trigger(law.potential),  # potential: <class 'eu5.eu5lib.Trigger'>
            'Allow': self.formatter.format_trigger(law.allow),  # allow: <class 'common.paradox_parser.Tree'>
            # 'Law Category': law.law_category_loc,  # law_category: <class 'str'>
            'Country': self.parser.localize(law.law_country_group) if law.law_country_group else '',  # law_country_group: <class 'str'>
            'Government type': self.parser.localize(law.law_gov_group) if law.law_gov_group else '',  # law_gov_group: <class 'str'>
            'Religion groups': self.create_wiki_list([self.parser.localize(law_religion_group) for law_religion_group in law.law_religion_group]),
            # law_religion_group: list[str]
            'Locked': self.formatter.format_trigger(law.locked),  # locked: <class 'eu5.eu5lib.Trigger'>
            'Requires Vote': '' if law.requires_vote is None else (
                '[[File:Yes.png|20px|Requires Vote]]' if law.requires_vote else '[[File:No.png|20px|Not Requires Vote]]'),
            # requires_vote: <class 'bool'>
            # 'Type': law.type,  # type  'str'
            'Unique': '' if law.unique is None else '[[File:Yes.png|20px|Unique]]' if law.unique else '[[File:No.png|20px|Not Unique]]',
            # unique: <class 'bool'>
            'Policies': self.get_law_policy_table(law.policies.values()),
        }

    def get_laws_as_sections(self, laws: Iterable[Law], section_level = 3) -> str:
        result = ['']
        ignored_attributes = ['Name', 'Policies']  # added in other ways
        attribute_map = {'Country': 'Only for',
                         'Government type': 'Only for',
                         'Religion groups': 'Requires one of the following religion groups',
                         }
        for law in laws:
            result.append(self.formatter.create_section_heading(law.display_name, section_level))
            result.append(f'{{{{iconbox||{law.description}|image={law.get_wiki_filename()}}}}}')
            law_data = self.get_law_data(law)
            for attribute, value in law_data.items():
                if attribute not in ignored_attributes and value is not None and len(value) > 0:
                    if attribute in attribute_map:
                        attribute = attribute_map[attribute]
                    result.append(f';{attribute}: {value}')
            result.append(law_data['Policies'])


        return '\n'.join(result)

    @staticmethod
    def _format_time_to_implement(policy: LawPolicy, ignore_default_years=2):
        days = policy.days
        weeks = policy.weeks
        months = policy.months
        years = policy.years

        if days >= 365:
            years += days // 365
            days = days % 365
        if weeks >= 52:
            years += weeks // 52
            weeks = weeks % 52
        if months >= 12:
            years += months // 12
            months = months % 12

        if years == ignore_default_years and days == weeks == months == 0:
            return ''
        result = []
        if years > 0:
            result.append(f'{years} years')
        if months > 0:
            result.append(f'{months} months')
        if weeks > 0:
            result.append(f'{weeks} weeks')
        if days > 0:
            result.append(f'{days} days')
        return '\n'.join(result)

    def get_law_policy_table(self, policies: Iterable[LawPolicy]):
        policy_table_data = [{
            'width=20% | Policy': f"'''{policy.display_name}'''\n\n<div class=\"hidem\" style=\"font-style: italic; font-size:smaller;\">{policy.description}</div>",
            'Allow': self.formatter.format_trigger(policy.allow),  # allow: <class 'eu5.eu5lib.Trigger'>
            'Country Modifier': self.format_modifier_section('country_modifier', policy),  # country_modifier: list[eu5.eu5lib.Eu5Modifier]
            'Estate Preferences': self.create_wiki_list([estate_preferences.get_wiki_link_with_icon() for estate_preferences in policy.estate_preferences]),
            # estate_preferences: list[str]
            'Time to implement': self._format_time_to_implement(policy, ignore_default_years=2),
            'On Activate': self.formatter.format_effect(policy.on_activate),  # on_activate: <class 'eu5.eu5lib.Effect'>
            'On Deactivate': self.formatter.format_effect(policy.on_deactivate),  # on_deactivate: <class 'eu5.eu5lib.Effect'>
            'On Pay Price': self.formatter.format_effect(policy.on_pay_price),  # on_pay_price: <class 'eu5.eu5lib.Effect'>
            'On Fully Activated': self.formatter.format_effect(policy.on_fully_activated),  # on_fully_activated: <class 'eu5.eu5lib.Effect'>
            'Potential': self.formatter.format_trigger(policy.potential),  # potential: <class 'eu5.eu5lib.Trigger'>
            'Price': policy.price.format(icon_only=True) if hasattr(policy.price, 'format') else policy.price,  # price: <class 'eu5.eu5lib.Price'>
            # TODO: AI preference wants_this_policy_bias should be included eventually
            # 'Wants This Policy Bias': '' if policy.wants_this_policy_bias is None else policy.wants_this_policy_bias,
            # wants_this_policy_bias
            'Diplomatic Capacity Cost': '' if policy.diplomatic_capacity_cost is None else policy.diplomatic_capacity_cost,
            # diplomatic_capacity_cost: <class 'str'>
            'Gold': '' if policy.gold is None else '[[File:Yes.png|20px|Gold]]' if policy.gold else '[[File:No.png|20px|Not Gold]]',  # gold: <class 'bool'>
            'Manpower': '' if policy.manpower is None else '[[File:Yes.png|20px|Manpower]]' if policy.manpower else '[[File:No.png|20px|Not Manpower]]',
            # manpower: <class 'bool'>
            'Allow Member Annexation': '' if policy.allow_member_annexation is None else '[[File:Yes.png|20px|Allow Member Annexation]]' if policy.allow_member_annexation else '[[File:No.png|20px|Not Allow Member Annexation]]',
            # allow_member_annexation: <class 'bool'>
            'Annexation Speed': '' if policy.annexation_speed is None else policy.annexation_speed,  # annexation_speed: <class 'float'>
            'Can Build Buildings In Members': '' if policy.can_build_buildings_in_members is None else '[[File:Yes.png|20px|Can Build Buildings In Members]]' if policy.can_build_buildings_in_members else '[[File:No.png|20px|Not Can Build Buildings In Members]]',
            # can_build_buildings_in_members: <class 'bool'>
            'Can Build Rgos In Members': '' if policy.can_build_rgos_in_members is None else '[[File:Yes.png|20px|Can Build Rgos In Members]]' if policy.can_build_rgos_in_members else '[[File:No.png|20px|Not Can Build Rgos In Members]]',
            # can_build_rgos_in_members: <class 'bool'>
            'Can Build Roads In Members': '' if policy.can_build_roads_in_members is None else '[[File:Yes.png|20px|Can Build Roads In Members]]' if policy.can_build_roads_in_members else '[[File:No.png|20px|Not Can Build Roads In Members]]',
            # can_build_roads_in_members: <class 'bool'>
            'Has Parliament': '' if policy.has_parliament is None else '[[File:Yes.png|20px|Has Parliament]]' if policy.has_parliament else '[[File:No.png|20px|Not Has Parliament]]',
            # has_parliament: <class 'bool'>
            'International Organization Modifier': self.format_modifier_section('international_organization_modifier', policy),
            # international_organization_modifier: list[eu5.eu5lib.Eu5Modifier]
            'Leader Change Method': '' if policy.leader_change_method is None else policy.leader_change_method,  # leader_change_method: <class 'str'>
            'Leader Change Trigger Type': '' if policy.leader_change_trigger_type is None else policy.leader_change_trigger_type,
            # leader_change_trigger_type: <class 'str'>
            'Leader Type': '' if policy.leader_type is None else policy.leader_type,  # leader_type: <class 'str'>
            'Leadership Election Resolution': '' if policy.leadership_election_resolution is None else policy.leadership_election_resolution,
            # leadership_election_resolution: <class 'str'>
            'Months Between Leader Changes': '' if policy.months_between_leader_changes is None else policy.months_between_leader_changes,
            # months_between_leader_changes: <class 'int'>
            'Opinion Bonus': '' if policy.opinion_bonus is None else policy.opinion_bonus,  # opinion_bonus: <class 'int'>
            'Payments Implemented': self.create_wiki_list(policy.payments_implemented),
            # payments_implemented: list[str]
            'Trust Bonus': '' if policy.trust_bonus is None else policy.trust_bonus,  # trust_bonus: <class 'int'>
        } for policy in policies]
        return "\n" + self.make_wiki_table(policy_table_data, table_classes=['mildtable', 'plainlist'],
                                    one_line_per_cell=True,
                                    remove_empty_columns=True,
                                    )
    def generate_parliament_issue_table(self):
        issues = [issue for issue in self.parser.parliament_issues.values() if issue.type == 'country']
        issue_table_data = [{
            # 'Parliament issue': f'{{{{iconbox|{issue.display_name}|{issue.description}|w=300px|image={issue.get_wiki_filename()}}}}}',
            'Parliament issue': f"'''{issue.display_name}'''\n\n<div class=\"hidem\" style=\"font-style: italic; font-size:smaller;\">{issue.description}</div>",
            'Requirements': self.formatter.format_trigger(issue.potential) + '\n' + self.formatter.format_trigger(issue.allow),
            'Chance': issue.chance.format() if hasattr(issue.chance, 'format') else issue.chance,
            'Estate': '' if issue.estate is None else issue.estate.get_wiki_link_with_icon() if issue.estate else '',
            'Modifiers while the issue is debated': self.format_modifier_section('modifier_when_in_debate', issue),
            'Effects if the issue is being resolved': self.formatter.format_effect(issue.on_debate_passed),
            'Effects if the issue fails': self.formatter.format_effect(issue.on_debate_failed),

            # for IO debates
            # 'Selectable For': self.formatter.format_trigger(issue.selectable_for),
            # selectable_for: <class 'eu5.trigger.Trigger'>
            # 'Special Status': '' if issue.special_status is None else issue.special_status.get_wiki_link_with_icon() if issue.special_status else '',
            # special_status: <class 'eu5.eu5lib.InternationalOrganizationSpecialStatus'>
            # 'AI voting criteria': '' if issue.wants_this_parliament_issue_bias is None else issue.wants_this_parliament_issue_bias.format() if hasattr(
            #     issue.wants_this_parliament_issue_bias, 'format') else issue.wants_this_parliament_issue_bias,
        } for issue in issues]
        return self.make_wiki_table(issue_table_data, table_classes=['mildtable', 'plainlist'],
                                    one_line_per_cell=True,
                                    remove_empty_columns=True,
                                    )


    # AUTOGENERATED

    def generate_advances_tables(self):
        result = []
        for age, table in self.get_advances_sections().items():
            result.append(self.formatter.create_section_heading(age))
            result.append(self.surround_with_autogenerated_section(age, table, add_version_header=True))
        return result

    def get_advances_sections(self):
        return {f'advances_{age}': self.get_advances_table(advances) for age, advances in unsorted_groupby(self.parser.advances.values(), key=lambda advance: advance.age.name)}

    def get_advances_table(self, advances: Iterable[Advance]):
        sorted_advances = sorted(advances, key=attrgetter('display_name'))
        advances_table_data = [{
            'Name': f'{{{{iconbox|{advance.display_name}|{advance.description}|w=300px|image={advance.get_wiki_filename()}}}}}',
            # 'Age': advance.age.get_wiki_link_with_icon(),
            'Ai Preference Tags': 'grota must implement or delete',  # ai_preference_tags: <class 'list'>
            'Ai Weight': '' if advance.ai_weight is None else self.create_wiki_list([f'{k}: ...' for k in advance.ai_weight.keys()]) if advance.ai_weight else '',  # ai_weight: <class 'common.paradox_parser.Tree'>
            'Allow': self.formatter.format_trigger(advance.allow),  # allow: <class 'eu5.trigger.Trigger'>
            'Allow Children': '[[File:Yes.png|20px|Allow Children]]' if advance.allow_children else '[[File:No.png|20px|Not Allow Children]]',  # allow_children: <class 'bool'>
            'Country Type': '' if advance.country_type is None else advance.country_type,  # country_type: <class 'str'>
            'Depth': '' if advance.depth is None else advance.depth,  # depth: <class 'int'>
            'Age Specialization': '' if advance.age_specialization is None else advance.age_specialization,  # age_specialization: <class 'str'>
            'Government': '' if advance.government is None else advance.government,  # government: <class 'str'>
            'In Tree Of': '' if advance.in_tree_of is None else advance.in_tree_of,  # in_tree_of: typing.Any
            'Modifier While Progressing': self.format_modifier_section('modifier_while_progressing', advance),  # modifier_while_progressing: list[eu5.eu5lib.Eu5Modifier]
            'Potential': self.formatter.format_trigger(advance.potential),  # potential: <class 'eu5.trigger.Trigger'>
            'Requires': self.create_wiki_list([requires.get_wiki_link_with_icon() if requires else '' for requires in advance.requires]),  # requires: list[eu5.eu5lib.Advance]
            'Research Cost': '' if advance.research_cost is None else advance.research_cost,  # research_cost: <class 'float'>
            'Starting Technology Level': advance.starting_technology_level,  # starting_technology_level: <class 'int'>
            'Unlock Ability': self.create_wiki_list([unlock_ability for unlock_ability in advance.unlock_ability]),  # unlock_ability: list[str]
            'Unlock Building': self.create_wiki_list([unlock_building for unlock_building in advance.unlock_building]),  # unlock_building: list[str]
            'Unlock Cabinet Action': self.create_wiki_list([unlock_cabinet_action for unlock_cabinet_action in advance.unlock_cabinet_action]),  # unlock_cabinet_action: list[str]
            'Unlock Casus Belli': self.create_wiki_list([unlock_casus_belli for unlock_casus_belli in advance.unlock_casus_belli]),  # unlock_casus_belli: list[str]
            'Unlock Country Interaction': self.create_wiki_list([unlock_country_interaction for unlock_country_interaction in advance.unlock_country_interaction]),  # unlock_country_interaction: list[str]
            'Unlock Diplomacy': self.create_wiki_list([unlock_diplomacy for unlock_diplomacy in advance.unlock_diplomacy]),  # unlock_diplomacy: list[str]
            'Unlock Estate Privilege': self.create_wiki_list([unlock_estate_privilege for unlock_estate_privilege in advance.unlock_estate_privilege]),  # unlock_estate_privilege: list[str]
            'Unlock Government Reform': self.create_wiki_list([unlock_government_reform for unlock_government_reform in advance.unlock_government_reform]),  # unlock_government_reform: list[str]
            'Unlock Heir Selection': self.create_wiki_list([unlock_heir_selection for unlock_heir_selection in advance.unlock_heir_selection]),  # unlock_heir_selection: list[str]
            'Unlock Law': self.create_wiki_list([unlock_law for unlock_law in advance.unlock_law]),  # unlock_law: list[str]
            'Unlock Levy': self.create_wiki_list([unlock_levy.display_name for unlock_levy in advance.unlock_levy]),  # unlock_levy: list[str]
            'Unlock Policy': self.create_wiki_list([unlock_policy for unlock_policy in advance.unlock_policy]),  # unlock_policy: list[str]
            'Unlock Production Method': self.create_wiki_list([unlock_production_method for unlock_production_method in advance.unlock_production_method]),  # unlock_production_method: list[str]
            'Unlock Road Type': self.create_wiki_list([unlock_road_type for unlock_road_type in advance.unlock_road_type]),  # unlock_road_type: list[str]
            'Unlock Subject Type': self.create_wiki_list([unlock_subject_type for unlock_subject_type in advance.unlock_subject_type]),  # unlock_subject_type: list[str]
            'Unlock Unit': self.create_wiki_list([unlock_unit for unlock_unit in advance.unlock_unit]),  # unlock_unit: list[str]

        } for advance in sorted_advances]
        return self.make_wiki_table(advances_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )
    def generate_cabinet_actions_table(self):
        cabinet_actions = self.parser.cabinet_actions.values()
        cabinet_actions_table_data = [{
            'Name': f'{{{{iconbox|{cabinet_action.display_name}|{cabinet_action.description}|w=300px|image={cabinet_action.get_wiki_filename()}}}}}',
            'Ability': cabinet_action.ability,  # ability: <class 'str'>
            'Ai Will Do': '' if cabinet_action.ai_will_do is None else cabinet_action.ai_will_do.format() if hasattr(cabinet_action.ai_will_do, 'format') else cabinet_action.ai_will_do,  # ai_will_do: <class 'eu5.eu5lib.ScriptValue'>
            'Allow': self.formatter.format_trigger(cabinet_action.allow),  # allow: <class 'eu5.trigger.Trigger'>
            'Allow Multiple': '' if cabinet_action.allow_multiple is None else '[[File:Yes.png|20px|Allow Multiple]]' if cabinet_action.allow_multiple else '[[File:No.png|20px|Not Allow Multiple]]',  # allow_multiple: <class 'bool'>
            'Country Modifier': self.format_modifier_section('country_modifier', cabinet_action),  # country_modifier: list[eu5.eu5lib.Eu5Modifier]
            'Days': cabinet_action.days,  # days: <class 'int'>
            'Forbid For Automation': '[[File:Yes.png|20px|Forbid For Automation]]' if cabinet_action.forbid_for_automation else '[[File:No.png|20px|Not Forbid For Automation]]',  # forbid_for_automation: <class 'bool'>
            'Is Finished': self.formatter.format_trigger(cabinet_action.is_finished),  # is_finished: <class 'eu5.trigger.Trigger'>
            'Location Modifier': self.format_modifier_section('location_modifier', cabinet_action),  # location_modifier: list[eu5.eu5lib.Eu5Modifier]
            'Map Marker': '' if cabinet_action.map_marker is None else self.create_wiki_list([f'{k}: ...' for k in cabinet_action.map_marker.keys()]) if cabinet_action.map_marker else '',  # map_marker: <class 'common.paradox_parser.Tree'>
            'Min': '' if cabinet_action.min is None else cabinet_action.min,  # min: <class 'int'>
            'On Activate': self.formatter.format_effect(cabinet_action.on_activate),  # on_activate: <class 'eu5.effect.Effect'>
            'On Deactivate': self.formatter.format_effect(cabinet_action.on_deactivate),  # on_deactivate: <class 'eu5.effect.Effect'>
            'On Fully Activated': self.formatter.format_effect(cabinet_action.on_fully_activated),  # on_fully_activated: <class 'eu5.effect.Effect'>
            'Potential': self.formatter.format_trigger(cabinet_action.potential),  # potential: <class 'eu5.trigger.Trigger'>
            'Progress': '' if cabinet_action.progress is None else cabinet_action.progress.format() if hasattr(cabinet_action.progress, 'format') else cabinet_action.progress,  # progress: <class 'eu5.eu5lib.ScriptValue'>
            'Province Modifier': self.format_modifier_section('province_modifier', cabinet_action),  # province_modifier: list[eu5.eu5lib.Eu5Modifier]
            # 'Select Trigger': '' if cabinet_action.select_trigger is None else self.create_wiki_list([f'{k}: ...' for k in cabinet_action.select_trigger.keys()]) if cabinet_action.select_trigger else '',  # select_trigger: <class 'common.paradox_parser.Tree'>
            'Societal Values': cabinet_action.societal_values,  # societal_values: <class 'float'>
            'Years': cabinet_action.years,  # years: <class 'int'>
        } for cabinet_action in cabinet_actions]
        return self.make_wiki_table(cabinet_actions_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )
    def generate_casus_belli_table(self):
        casus_bellis = self.parser.casus_belli.values()
        casus_belli_table_data = [{
            'Name': f'{{{{iconbox|{casus_belli.display_name}|{casus_belli.description}|w=300px|image={casus_belli.get_wiki_filename()}}}}}',
            'Additional War Enthusiasm': casus_belli.additional_war_enthusiasm,  # additional_war_enthusiasm: <class 'float'>
            'Additional War Enthusiasm Attacker': casus_belli.additional_war_enthusiasm_attacker,  # additional_war_enthusiasm_attacker: <class 'float'>
            'Additional War Enthusiasm Defender': casus_belli.additional_war_enthusiasm_defender,  # additional_war_enthusiasm_defender: <class 'float'>
            'Ai Cede Location Desire': '' if casus_belli.ai_cede_location_desire is None else casus_belli.ai_cede_location_desire.format() if hasattr(casus_belli.ai_cede_location_desire, 'format') else casus_belli.ai_cede_location_desire,  # ai_cede_location_desire: <class 'eu5.eu5lib.ScriptValue'>
            'Ai Cede Province Desire': '' if casus_belli.ai_cede_province_desire is None else casus_belli.ai_cede_province_desire.format() if hasattr(casus_belli.ai_cede_province_desire, 'format') else casus_belli.ai_cede_province_desire,  # ai_cede_province_desire: <class 'eu5.eu5lib.ScriptValue'>
            'Ai Selection Desire': '' if casus_belli.ai_selection_desire is None else casus_belli.ai_selection_desire.format() if hasattr(casus_belli.ai_selection_desire, 'format') else casus_belli.ai_selection_desire,  # ai_selection_desire: <class 'eu5.eu5lib.ScriptValue'>
            'Ai Subjugation Desire': casus_belli.ai_subjugation_desire,  # ai_subjugation_desire: <class 'int'>
            'Allow Creation': self.formatter.format_trigger(casus_belli.allow_creation),  # allow_creation: <class 'eu5.trigger.Trigger'>
            'Allow Declaration': self.formatter.format_trigger(casus_belli.allow_declaration),  # allow_declaration: <class 'eu5.trigger.Trigger'>
            'Allow Ports For Reach Ai': '[[File:Yes.png|20px|Allow Ports For Reach Ai]]' if casus_belli.allow_ports_for_reach_ai else '[[File:No.png|20px|Not Allow Ports For Reach Ai]]',  # allow_ports_for_reach_ai: <class 'bool'>
            'Allow Release Areas': '[[File:Yes.png|20px|Allow Release Areas]]' if casus_belli.allow_release_areas else '[[File:No.png|20px|Not Allow Release Areas]]',  # allow_release_areas: <class 'bool'>
            'Allow Separate Peace': '[[File:Yes.png|20px|Allow Separate Peace]]' if casus_belli.allow_separate_peace else '[[File:No.png|20px|Not Allow Separate Peace]]',  # allow_separate_peace: <class 'bool'>
            'Antagonism Reduction Per Warworth Defender': casus_belli.antagonism_reduction_per_warworth_defender,  # antagonism_reduction_per_warworth_defender: <class 'float'>
            'Can Expire': '[[File:Yes.png|20px|Can Expire]]' if casus_belli.can_expire else '[[File:No.png|20px|Not Can Expire]]',  # can_expire: <class 'bool'>
            'Cut Down In Size Cb': '[[File:Yes.png|20px|Cut Down In Size Cb]]' if casus_belli.cut_down_in_size_cb else '[[File:No.png|20px|Not Cut Down In Size Cb]]',  # cut_down_in_size_cb: <class 'bool'>
            'Max Warscore From Battles': casus_belli.max_warscore_from_battles,  # max_warscore_from_battles: <class 'int'>
            'No Cb': '' if casus_belli.no_cb is None else '[[File:Yes.png|20px|No Cb]]' if casus_belli.no_cb else '[[File:No.png|20px|Not No Cb]]',  # no_cb: <class 'bool'>
            'Province': self.formatter.format_trigger(casus_belli.province),  # province: <class 'eu5.trigger.Trigger'>
            'Speed': casus_belli.speed,  # speed: <class 'float'>
            'Trade': '[[File:Yes.png|20px|Trade]]' if casus_belli.trade else '[[File:No.png|20px|Not Trade]]',  # trade: <class 'bool'>
            'Visible': self.formatter.format_trigger(casus_belli.visible),  # visible: <class 'eu5.trigger.Trigger'>
            'War Goal Type': casus_belli.war_goal_type.get_wiki_link_with_icon() if casus_belli.war_goal_type else '',  # war_goal_type: <class 'eu5.eu5lib.Wargoal'>
        } for casus_belli in casus_bellis]
        return self.make_wiki_table(casus_belli_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )
    def generate_cultures_table(self):
        cultures = sorted(self.parser.cultures.values(), key=lambda culture: (culture.culture_groups, culture.display_name))
        cultures_table_data = [{
            'Name': f' style="background-color: {culture.color.get_css_color_string() if culture.color else "white"}" | ' + culture.display_name,
            'Adjective Keys': self.create_wiki_list([adjective_keys for adjective_keys in culture.adjective_keys]),  # adjective_keys: list[str]
            'Character Modifier': self.format_modifier_section('character_modifier', culture),  # character_modifier: list[eu5.eu5lib.Eu5Modifier]
            'Country Modifier': self.format_modifier_section('country_modifier', culture),  # country_modifier: list[eu5.eu5lib.Eu5Modifier]
            'Culture Groups': self.create_wiki_list([culture_groups.display_name if culture_groups else '' for culture_groups in culture.culture_groups]),  # culture_groups: list[eu5.eu5lib.CultureGroup]
            'Dynasty Name Type': culture.dynasty_name_type,  # dynasty_name_type: <class 'str'>
            'Language': culture.language if isinstance(culture.language, str) else culture.language.display_name if culture.language else '',  # language: <class 'eu5.eu5lib.Language'>
            'Location Modifier': self.format_modifier_section('location_modifier', culture),  # location_modifier: list[eu5.eu5lib.Eu5Modifier]
            'Noun Keys': self.create_wiki_list([noun_keys for noun_keys in culture.noun_keys]),  # noun_keys: list[str]
            'Opinions': '' if culture.opinions is None else self.create_wiki_list([f'{k}: ...' for k in culture.opinions.keys()]) if culture.opinions else '',  # opinions: <class 'common.paradox_parser.Tree'>
            'Tags': self.create_wiki_list([tags for tags in culture.tags]),  # tags: list[str]
            'Use Patronym': '[[File:Yes.png|20px|Use Patronym]]' if culture.use_patronym else '[[File:No.png|20px|Not Use Patronym]]',  # use_patronym: <class 'bool'>
        } for culture in cultures]
        return self.make_wiki_table(cultures_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )
    def generate_government_reforms_table(self):
        government_reforms = self.parser.government_reforms.values()
        government_reforms_table_data = [{
            'Name': f'{{{{iconbox|{government_reform.display_name}|{government_reform.description}|w=300px|image={government_reform.get_wiki_filename()}}}}}',
            'Age': '' if government_reform.age is None else government_reform.age.get_wiki_link_with_icon() if government_reform.age else '',  # age: <class 'eu5.eu5lib.Age'>
            'Allow': self.formatter.format_trigger(government_reform.allow),  # allow: <class 'eu5.trigger.Trigger'>
            'Block For Rebel': '[[File:Yes.png|20px|Block For Rebel]]' if government_reform.block_for_rebel else '[[File:No.png|20px|Not Block For Rebel]]',  # block_for_rebel: <class 'bool'>
            'Country Modifier': self.format_modifier_section('country_modifier', government_reform),  # country_modifier: list[eu5.eu5lib.Eu5Modifier]
            'Government': '' if government_reform.government is None else government_reform.government.get_wiki_link_with_icon() if government_reform.government else '',  # government: <class 'eu5.eu5lib.GovernmentType'>
            'Location Modifier': self.format_modifier_section('location_modifier', government_reform),  # location_modifier: list[eu5.eu5lib.Eu5Modifier]
            'Locked': self.formatter.format_trigger(government_reform.locked),  # locked: <class 'eu5.trigger.Trigger'>
            'Major': '[[File:Yes.png|20px|Major]]' if government_reform.major else '[[File:No.png|20px|Not Major]]',  # major: <class 'bool'>
            'Male Regnal Names': self.create_wiki_list([male_regnal_names for male_regnal_names in government_reform.male_regnal_names]),  # male_regnal_names: list[str]
            'Months': government_reform.months,  # months: <class 'int'>
            'On Activate': self.formatter.format_effect(government_reform.on_activate),  # on_activate: <class 'eu5.effect.Effect'>
            'On Deactivate': self.formatter.format_effect(government_reform.on_deactivate),  # on_deactivate: <class 'eu5.effect.Effect'>
            'Potential': self.formatter.format_trigger(government_reform.potential),  # potential: <class 'eu5.trigger.Trigger'>
            'Societal Values': self.create_wiki_list([societal_values for societal_values in government_reform.societal_values]),  # societal_values: list[str]
            'Unique': '[[File:Yes.png|20px|Unique]]' if government_reform.unique else '[[File:No.png|20px|Not Unique]]',  # unique: <class 'bool'>
            'Years': '' if government_reform.years is None else government_reform.years,  # years: <class 'float'>
        } for government_reform in government_reforms]
        return self.make_wiki_table(government_reforms_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )
    def generate_holy_sites_table(self):
        holy_sites = self.parser.holy_sites.values()
        holy_sites_table_data = [{
            'Name': holy_site.display_name,
            'Avatar': '' if holy_site.avatar is None else holy_site.avatar.get_wiki_link_with_icon() if holy_site.avatar else '',  # avatar: <class 'eu5.eu5lib.Avatar'>
            'God': '' if holy_site.god is None else holy_site.god.get_wiki_link_with_icon() if holy_site.god else '',  # god: <class 'eu5.eu5lib.God'>
            'Importance': holy_site.importance,  # importance: <class 'int'>
            'Location': holy_site.location.display_name if holy_site.location else '',  # location: <class 'eu5.eu5lib.Location'>
            'Religions': self.create_wiki_list([religions.get_wiki_link_with_icon() if religions else '' for religions in holy_site.religions]),  # religions: list[eu5.eu5lib.Religion]
            'Type': holy_site.type.get_wiki_link_with_icon() if holy_site.type else '',  # type: <class 'eu5.eu5lib.HolySiteType'>
        } for holy_site in holy_sites]
        return self.make_wiki_table(holy_sites_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )
    def generate_languages_table(self):
        languages = self.parser.languages.values()
        languages_table_data = [{
            'Name': f' style="background-color: {language.color.get_css_color_string() if language.color else "white"}" | ' + language.display_name,
            'Character Name Order': language.character_name_order,  # character_name_order: <class 'str'>
            'Character Name Short Regnal Number': language.character_name_short_regnal_number,  # character_name_short_regnal_number: <class 'str'>
            'Descendant Prefix': language.descendant_prefix,  # descendant_prefix: <class 'str'>
            'Descendant Prefix Female': language.descendant_prefix_female,  # descendant_prefix_female: <class 'str'>
            'Descendant Prefix Male': language.descendant_prefix_male,  # descendant_prefix_male: <class 'str'>
            'Descendant Suffix': language.descendant_suffix,  # descendant_suffix: <class 'str'>
            'Descendant Suffix Female': language.descendant_suffix_female,  # descendant_suffix_female: <class 'str'>
            'Descendant Suffix Male': language.descendant_suffix_male,  # descendant_suffix_male: <class 'str'>
            'Dialects': '' if language.dialects is None else self.create_wiki_list([f'{k}: ...' for k in language.dialects.keys()]) if language.dialects else '',  # dialects: <class 'common.paradox_parser.Tree'>
            'Dynasty Names': self.create_wiki_list([dynasty_names for dynasty_names in language.dynasty_names]),  # dynasty_names: list[str]
            'Dynasty Template Keys': self.create_wiki_list([dynasty_template_keys for dynasty_template_keys in language.dynasty_template_keys]),  # dynasty_template_keys: list[str]
            'Fallback': language.fallback if isinstance(language.fallback, str) else '' if language.fallback is None else language.fallback.display_name if language.fallback else '',  # fallback: <class 'eu5.eu5lib.Language'>
            'Family': '' if language.family is None else language.family.display_name if language.family else '',  # family: <class 'eu5.eu5lib.LanguageFamily'>
            'Female Names': self.create_wiki_list([female_names for female_names in language.female_names]),  # female_names: list[str]
            'First Name Conjoiner': language.first_name_conjoiner,  # first_name_conjoiner: <class 'str'>
            'Location Prefix': language.location_prefix,  # location_prefix: <class 'str'>
            'Location Prefix Ancient': language.location_prefix_ancient,  # location_prefix_ancient: <class 'str'>
            'Location Prefix Ancient Vowel': language.location_prefix_ancient_vowel,  # location_prefix_ancient_vowel: <class 'str'>
            'Location Prefix Elision': self.create_wiki_list([location_prefix_elision for location_prefix_elision in language.location_prefix_elision]),  # location_prefix_elision: list[str]
            'Location Prefix Vowel': language.location_prefix_vowel,  # location_prefix_vowel: <class 'str'>
            'Location Suffix': language.location_suffix,  # location_suffix: <class 'str'>
            'Lowborn': self.create_wiki_list([lowborn for lowborn in language.lowborn]),  # lowborn: list[str]
            'Male Names': self.create_wiki_list([male_names for male_names in language.male_names]),  # male_names: list[str]
            'Patronym Prefix Daughter': language.patronym_prefix_daughter,  # patronym_prefix_daughter: <class 'str'>
            'Patronym Prefix Daughter Vowel': language.patronym_prefix_daughter_vowel,  # patronym_prefix_daughter_vowel: <class 'str'>
            'Patronym Prefix Son': language.patronym_prefix_son,  # patronym_prefix_son: <class 'str'>
            'Patronym Prefix Son Vowel': language.patronym_prefix_son_vowel,  # patronym_prefix_son_vowel: <class 'str'>
            'Patronym Suffix': language.patronym_suffix,  # patronym_suffix: <class 'str'>
            'Patronym Suffix Daughter': language.patronym_suffix_daughter,  # patronym_suffix_daughter: <class 'str'>
            'Patronym Suffix Son': language.patronym_suffix_son,  # patronym_suffix_son: <class 'str'>
            'Require Genitive Location Names': '[[File:Yes.png|20px|Require Genitive Location Names]]' if language.require_genitive_location_names else '[[File:No.png|20px|Not Require Genitive Location Names]]',  # require_genitive_location_names: <class 'bool'>
            'Ship Names': self.create_wiki_list([ship_names for ship_names in language.ship_names]),  # ship_names: list[str]
        } for language in languages]
        return self.make_wiki_table(languages_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )
    def generate_levies_table(self):
        levies = self.parser.levies.values()
        levies_table_data = [{
            'Name': levy.display_name,
            'Allow': self.formatter.format_trigger(levy.allow),  # allow: <class 'eu5.trigger.Trigger'>
            'Allow As Crew': self.formatter.format_trigger(levy.allow_as_crew),  # allow_as_crew: <class 'eu5.trigger.Trigger'>
            'Allowed Culture': self.create_wiki_list([allowed_culture.display_name if allowed_culture else '' for allowed_culture in levy.allowed_culture]),  # allowed_culture: list[eu5.eu5lib.Culture]
            'Allowed Pop Type': self.create_wiki_list([allowed_pop_type.get_wiki_link_with_icon() if allowed_pop_type else '' for allowed_pop_type in levy.allowed_pop_type]),  # allowed_pop_type: list[eu5.eu5lib.PopType]
            'Country Allow': self.formatter.format_trigger(levy.country_allow),  # country_allow: <class 'eu5.trigger.Trigger'>
            'Size': levy.size,  # size: <class 'float'>
            'Unit': levy.unit.get_wiki_link_with_icon() if levy.unit else '',  # unit: <class 'eu5.eu5lib.UnitType'>
        } for levy in levies]
        return self.make_wiki_table(levies_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )
    def generate_parliament_agendas_table(self):
        parliament_agendas = self.parser.parliament_agendas.values()
        parliament_agendas_table_data = [{
            'Name': parliament_agenda.display_name,
            'Ai Will Do': '' if parliament_agenda.ai_will_do is None else parliament_agenda.ai_will_do.format() if hasattr(parliament_agenda.ai_will_do, 'format') else parliament_agenda.ai_will_do,  # ai_will_do: <class 'eu5.eu5lib.ScriptValue'>
            'Allow': self.formatter.format_trigger(parliament_agenda.allow),  # allow: <class 'eu5.trigger.Trigger'>
            'Can Bribe': self.formatter.format_trigger(parliament_agenda.can_bribe),  # can_bribe: <class 'eu5.trigger.Trigger'>
            'Chance': parliament_agenda.chance,  # chance: <class 'int'>
            'Estate': self.create_wiki_list([estate.get_wiki_link_with_icon() if estate else '' for estate in parliament_agenda.estate]),  # estate: list[eu5.eu5lib.Estate]
            'Importance': parliament_agenda.importance,  # importance: <class 'float'>
            'On Accept': self.formatter.format_effect(parliament_agenda.on_accept),  # on_accept: <class 'eu5.effect.Effect'>
            'On Bribe': self.formatter.format_effect(parliament_agenda.on_bribe),  # on_bribe: <class 'eu5.effect.Effect'>
            'Potential': self.formatter.format_trigger(parliament_agenda.potential),  # potential: <class 'eu5.trigger.Trigger'>
            'Special Status': '' if parliament_agenda.special_status is None else parliament_agenda.special_status,  # special_status: typing.Any
            'Type': parliament_agenda.type,  # type: <class 'str'>
        } for parliament_agenda in parliament_agendas]
        return self.make_wiki_table(parliament_agendas_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )
    def generate_peace_treaties_table(self):
        peace_treaties = self.parser.peace_treaties.values()
        peace_treaties_table_data = [{
            'Name': f'{{{{iconbox|{peace_treaty.display_name}|{peace_treaty.description}|w=300px|image={peace_treaty.get_wiki_filename()}}}}}',
            'Ai Desire': '' if peace_treaty.ai_desire is None else peace_treaty.ai_desire.format() if hasattr(peace_treaty.ai_desire, 'format') else peace_treaty.ai_desire,  # ai_desire: <class 'eu5.eu5lib.ScriptValue'>
            'Allow': self.formatter.format_trigger(peace_treaty.allow),  # allow: <class 'eu5.trigger.Trigger'>
            'Antagonism Type': '' if peace_treaty.antagonism_type is None else peace_treaty.antagonism_type.display_name if peace_treaty.antagonism_type else '',  # antagonism_type: <class 'eu5.eu5lib.Bias'>
            'Are Targets Exclusive': '[[File:Yes.png|20px|Are Targets Exclusive]]' if peace_treaty.are_targets_exclusive else '[[File:No.png|20px|Not Are Targets Exclusive]]',  # are_targets_exclusive: <class 'bool'>
            'Base Antagonism': '' if peace_treaty.base_antagonism is None else peace_treaty.base_antagonism.format() if hasattr(peace_treaty.base_antagonism, 'format') else peace_treaty.base_antagonism,  # base_antagonism: <class 'eu5.eu5lib.ScriptValue'>
            'Blocks Full Annexation': '[[File:Yes.png|20px|Blocks Full Annexation]]' if peace_treaty.blocks_full_annexation else '[[File:No.png|20px|Not Blocks Full Annexation]]',  # blocks_full_annexation: <class 'bool'>
            'Category': peace_treaty.category,  # category: <class 'str'>
            'Cost': peace_treaty.cost.format() if hasattr(peace_treaty.cost, 'format') else peace_treaty.cost,  # cost: <class 'eu5.eu5lib.ScriptValue'>
            'Effect': self.formatter.format_effect(peace_treaty.effect),  # effect: <class 'eu5.effect.Effect'>
            'Potential': self.formatter.format_trigger(peace_treaty.potential),  # potential: <class 'eu5.trigger.Trigger'>
            'Select Trigger': '' if peace_treaty.select_trigger is None else self.create_wiki_list([f'{k}: ...' for k in peace_treaty.select_trigger.keys()]) if peace_treaty.select_trigger else '',  # select_trigger: <class 'common.paradox_parser.Tree'>
        } for peace_treaty in peace_treaties]
        return self.make_wiki_table(peace_treaties_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )

    def get_sections(self, parser_attribute, groupby: str):
        sections = {}
        for category, traits in unsorted_groupby(entities, key=attrgetter(groupby)):
            traits = sorted(traits, key=attrgetter('display_name'))
            sections[f'traits_{category}'] = self.get_trait_table(traits)

    def generate_religions_table(self):
        religions = self.parser.religions.values()
        religions_table_data = [{
            'Name': f' style="background-color: {religion.color.get_css_color_string() if religion.color else "white"}" | ' + f'{{{{iconbox|{religion.display_name}|{religion.description}|w=300px|image={religion.get_wiki_filename()}}}}}',
            'Ai Wants Convert': '[[File:Yes.png|20px|Ai Wants Convert]]' if religion.ai_wants_convert else '[[File:No.png|20px|Not Ai Wants Convert]]',  # ai_wants_convert: <class 'bool'>
            'Culture Locked': '[[File:Yes.png|20px|Culture Locked]]' if religion.culture_locked else '[[File:No.png|20px|Not Culture Locked]]',  # culture_locked: <class 'bool'>
            'Custom Tags': self.create_wiki_list([custom_tags for custom_tags in religion.custom_tags]),  # custom_tags: list[str]
            'Definition Modifier': self.format_modifier_section('definition_modifier', religion),  # definition_modifier: list[eu5.eu5lib.Eu5Modifier]
            'Enable': religion.enable,  # enable: <class 'str'>
            'Factions': self.create_wiki_list([factions.get_wiki_link_with_icon() if factions else '' for factions in religion.factions]),  # factions: list[eu5.eu5lib.ReligiousFaction]
            'Group': '' if religion.group is None else religion.group.display_name if religion.group else '',  # group: <class 'eu5.eu5lib.ReligionGroup'>
            'Has Autocephalous Patriarchates': '[[File:Yes.png|20px|Has Autocephalous Patriarchates]]' if religion.has_autocephalous_patriarchates else '[[File:No.png|20px|Not Has Autocephalous Patriarchates]]',  # has_autocephalous_patriarchates: <class 'bool'>
            'Has Avatars': '[[File:Yes.png|20px|Has Avatars]]' if religion.has_avatars else '[[File:No.png|20px|Not Has Avatars]]',  # has_avatars: <class 'bool'>
            'Has Canonization': '[[File:Yes.png|20px|Has Canonization]]' if religion.has_canonization else '[[File:No.png|20px|Not Has Canonization]]',  # has_canonization: <class 'bool'>
            'Has Cardinals': '[[File:Yes.png|20px|Has Cardinals]]' if religion.has_cardinals else '[[File:No.png|20px|Not Has Cardinals]]',  # has_cardinals: <class 'bool'>
            'Has Doom': '[[File:Yes.png|20px|Has Doom]]' if religion.has_doom else '[[File:No.png|20px|Not Has Doom]]',  # has_doom: <class 'bool'>
            'Has Honor': '[[File:Yes.png|20px|Has Honor]]' if religion.has_honor else '[[File:No.png|20px|Not Has Honor]]',  # has_honor: <class 'bool'>
            'Has Karma': '[[File:Yes.png|20px|Has Karma]]' if religion.has_karma else '[[File:No.png|20px|Not Has Karma]]',  # has_karma: <class 'bool'>
            'Has Patriarchs': '[[File:Yes.png|20px|Has Patriarchs]]' if religion.has_patriarchs else '[[File:No.png|20px|Not Has Patriarchs]]',  # has_patriarchs: <class 'bool'>
            'Has Purity': '[[File:Yes.png|20px|Has Purity]]' if religion.has_purity else '[[File:No.png|20px|Not Has Purity]]',  # has_purity: <class 'bool'>
            'Has Religious Head': '[[File:Yes.png|20px|Has Religious Head]]' if religion.has_religious_head else '[[File:No.png|20px|Not Has Religious Head]]',  # has_religious_head: <class 'bool'>
            'Has Religious Influence': '[[File:Yes.png|20px|Has Religious Influence]]' if religion.has_religious_influence else '[[File:No.png|20px|Not Has Religious Influence]]',  # has_religious_influence: <class 'bool'>
            'Has Rite Power': '[[File:Yes.png|20px|Has Rite Power]]' if religion.has_rite_power else '[[File:No.png|20px|Not Has Rite Power]]',  # has_rite_power: <class 'bool'>
            'Has Yanantin': '[[File:Yes.png|20px|Has Yanantin]]' if religion.has_yanantin else '[[File:No.png|20px|Not Has Yanantin]]',  # has_yanantin: <class 'bool'>
            'Important Country': religion.important_country.get_wiki_link_with_icon() if religion.important_country else '',  # important_country: <class 'eu5.eu5lib.Country'>
            'Language': religion.language if isinstance(religion.language, str) else '' if religion.language is None else religion.language.display_name if religion.language else '',  # language: <class 'eu5.eu5lib.Language'>
            'Max Religious Figures For Religion': '' if religion.max_religious_figures_for_religion is None else religion.max_religious_figures_for_religion.format() if hasattr(religion.max_religious_figures_for_religion, 'format') else religion.max_religious_figures_for_religion,  # max_religious_figures_for_religion: <class 'eu5.eu5lib.ScriptValue'>
            'Max Sects': religion.max_sects,  # max_sects: <class 'int'>
            'Needs Reform': '[[File:Yes.png|20px|Needs Reform]]' if religion.needs_reform else '[[File:No.png|20px|Not Needs Reform]]',  # needs_reform: <class 'bool'>
            'Num Religious Focuses Needed For Reform': religion.num_religious_focuses_needed_for_reform,  # num_religious_focuses_needed_for_reform: <class 'int'>
            'Opinions': '' if religion.opinions is None else self.create_wiki_list([f'{k}: ...' for k in religion.opinions.keys()]) if religion.opinions else '',  # opinions: <class 'common.paradox_parser.Tree'>
            'Religious Aspects': religion.religious_aspects,  # religious_aspects: <class 'int'>
            'Religious Focuses': self.create_wiki_list([religious_focuses.get_wiki_link_with_icon() if religious_focuses else '' for religious_focuses in religion.religious_focuses]),  # religious_focuses: list[eu5.eu5lib.ReligiousFocus]
            '[RELIGIOUS_SCHOOL.GetName]': self.create_wiki_list([religious_school.get_wiki_link_with_icon() if religious_school else '' for religious_school in religion.religious_school]),  # religious_school: list[eu5.eu5lib.ReligiousSchool]
            'Tags': self.create_wiki_list([tags for tags in religion.tags]),  # tags: list[str]
            'Tithe': religion.tithe,  # tithe: <class 'float'>
            'Unique Names': self.create_wiki_list([unique_names for unique_names in religion.unique_names]),  # unique_names: list[str]
            'Use Icons': '[[File:Yes.png|20px|Use Icons]]' if religion.use_icons else '[[File:No.png|20px|Not Use Icons]]',  # use_icons: <class 'bool'>
        } for religion in religions]
        return self.make_wiki_table(religions_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )
    def generate_religious_aspects_table(self):
        religious_aspects = self.parser.religious_aspects.values()
        religious_aspects_table_data = [{
            'Name': f'{{{{iconbox|{religious_aspect.display_name}|{religious_aspect.description}|w=300px|image={religious_aspect.get_wiki_filename()}}}}}',
            'Modifier': self.format_modifier_section('modifier', religious_aspect),  # modifier: list[eu5.eu5lib.Eu5Modifier]
            'Enabled': self.formatter.format_trigger(religious_aspect.enabled),  # enabled: <class 'eu5.trigger.Trigger'>
            'Opinions': '' if religious_aspect.opinions is None else self.create_wiki_list([f'{k.get_wiki_link_with_icon()}: {v}' for k, v in religious_aspect.opinions.items()]),
            'Religion': self.create_wiki_list([religion.get_wiki_link_with_icon() if religion else '' for religion in religious_aspect.religion]),  # religion: list[eu5.eu5lib.Religion]
            'Visible': self.formatter.format_trigger(religious_aspect.visible),  # visible: <class 'eu5.trigger.Trigger'>
        } for religious_aspect in religious_aspects]
        return self.make_wiki_table(religious_aspects_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )
    def generate_religious_schools_table(self):
        religious_schools = self.parser.religious_schools.values()
        religious_schools_table_data = [{
            'Name': f'{{{{iconbox|{religious_school.display_name}|{religious_school.description}|w=300px|image={religious_school.get_wiki_filename()}}}}}',
            'Modifier': self.format_modifier_section('modifier', religious_school),  # modifier: list[eu5.eu5lib.Eu5Modifier]
            'Enabled For Character': self.formatter.format_trigger(religious_school.enabled_for_character),  # enabled_for_character: <class 'eu5.trigger.Trigger'>
            'Enabled For Country': self.formatter.format_trigger(religious_school.enabled_for_country),  # enabled_for_country: <class 'eu5.trigger.Trigger'>
        } for religious_school in religious_schools]
        return self.make_wiki_table(religious_schools_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )
    def generate_subject_types_table(self):
        subject_types = self.parser.subject_types.values()
        subject_types_table_data = [{
            'Name': f' style="background-color: {subject_type.color.get_css_color_string() if subject_type.color else "white"}" | ' + f'{{{{iconbox|{subject_type.display_name}|{subject_type.description}|w=300px|image={subject_type.get_wiki_filename()}}}}}',
            'Ai Wants To Be Overlord': '' if subject_type.ai_wants_to_be_overlord is None else subject_type.ai_wants_to_be_overlord.format() if hasattr(subject_type.ai_wants_to_be_overlord, 'format') else subject_type.ai_wants_to_be_overlord,  # ai_wants_to_be_overlord: <class 'eu5.eu5lib.ScriptValue'>
            'Allow Declaring Wars': '[[File:Yes.png|20px|Allow Declaring Wars]]' if subject_type.allow_declaring_wars else '[[File:No.png|20px|Not Allow Declaring Wars]]',  # allow_declaring_wars: <class 'bool'>
            'Annexation Min Opinion': subject_type.annexation_min_opinion,  # annexation_min_opinion: <class 'int'>
            'Annexation Min Years Before': '' if subject_type.annexation_min_years_before is None else subject_type.annexation_min_years_before,  # annexation_min_years_before: <class 'int'>
            'Annexation Speed': subject_type.annexation_speed,  # annexation_speed: <class 'int'>
            'Annexation Stall Opinion': subject_type.annexation_stall_opinion,  # annexation_stall_opinion: <class 'int'>
            'Can Attack': self.formatter.format_trigger(subject_type.can_attack),  # can_attack: <class 'eu5.trigger.Trigger'>
            'Can Be Force Broken In Peace Treaty': '[[File:Yes.png|20px|Can Be Force Broken In Peace Treaty]]' if subject_type.can_be_force_broken_in_peace_treaty else '[[File:No.png|20px|Not Can Be Force Broken In Peace Treaty]]',  # can_be_force_broken_in_peace_treaty: <class 'bool'>
            'Can Change Heir Selection': '[[File:Yes.png|20px|Can Change Heir Selection]]' if subject_type.can_change_heir_selection else '[[File:No.png|20px|Not Can Change Heir Selection]]',  # can_change_heir_selection: <class 'bool'>
            'Can Change Rank': '[[File:Yes.png|20px|Can Change Rank]]' if subject_type.can_change_rank else '[[File:No.png|20px|Not Can Change Rank]]',  # can_change_rank: <class 'bool'>
            'Can Overlord Build Buildings': '[[File:Yes.png|20px|Can Overlord Build Buildings]]' if subject_type.can_overlord_build_buildings else '[[File:No.png|20px|Not Can Overlord Build Buildings]]',  # can_overlord_build_buildings: <class 'bool'>
            'Can Overlord Build Rgos': '[[File:Yes.png|20px|Can Overlord Build Rgos]]' if subject_type.can_overlord_build_rgos else '[[File:No.png|20px|Not Can Overlord Build Rgos]]',  # can_overlord_build_rgos: <class 'bool'>
            'Can Overlord Build Roads': '[[File:Yes.png|20px|Can Overlord Build Roads]]' if subject_type.can_overlord_build_roads else '[[File:No.png|20px|Not Can Overlord Build Roads]]',  # can_overlord_build_roads: <class 'bool'>
            'Can Overlord Build Ships': '[[File:Yes.png|20px|Can Overlord Build Ships]]' if subject_type.can_overlord_build_ships else '[[File:No.png|20px|Not Can Overlord Build Ships]]',  # can_overlord_build_ships: <class 'bool'>
            'Can Overlord Recruit Regiments': '[[File:Yes.png|20px|Can Overlord Recruit Regiments]]' if subject_type.can_overlord_recruit_regiments else '[[File:No.png|20px|Not Can Overlord Recruit Regiments]]',  # can_overlord_recruit_regiments: <class 'bool'>
            'Can Rival': self.formatter.format_trigger(subject_type.can_rival),  # can_rival: <class 'eu5.trigger.Trigger'>
            'Creation Visible': self.formatter.format_trigger(subject_type.creation_visible),  # creation_visible: <class 'eu5.trigger.Trigger'>
            'Diplo Chance Accept Overlord': '' if subject_type.diplo_chance_accept_overlord is None else self.create_wiki_list([f'{k}: ...' for k in subject_type.diplo_chance_accept_overlord.keys()]) if subject_type.diplo_chance_accept_overlord else '',  # diplo_chance_accept_overlord: <class 'common.paradox_parser.Tree'>
            'Diplo Chance Accept Subject': '' if subject_type.diplo_chance_accept_subject is None else self.create_wiki_list([f'{k}: ...' for k in subject_type.diplo_chance_accept_subject.keys()]) if subject_type.diplo_chance_accept_subject else '',  # diplo_chance_accept_subject: <class 'common.paradox_parser.Tree'>
            'Diplomatic Capacity Cost Scale': subject_type.diplomatic_capacity_cost_scale,  # diplomatic_capacity_cost_scale: <class 'float'>
            'Enabled Through Diplomacy': self.formatter.format_trigger(subject_type.enabled_through_diplomacy),  # enabled_through_diplomacy: <class 'eu5.trigger.Trigger'>
            'Fleet Basing Rights': '[[File:Yes.png|20px|Fleet Basing Rights]]' if subject_type.fleet_basing_rights else '[[File:No.png|20px|Not Fleet Basing Rights]]',  # fleet_basing_rights: <class 'bool'>
            'Food Access': '[[File:Yes.png|20px|Food Access]]' if subject_type.food_access else '[[File:No.png|20px|Not Food Access]]',  # food_access: <class 'bool'>
            'Government': '' if subject_type.government is None else subject_type.government.get_wiki_link_with_icon() if subject_type.government else '',  # government: <class 'eu5.eu5lib.GovernmentType'>
            'Great Power Score Transfer': subject_type.great_power_score_transfer,  # great_power_score_transfer: <class 'float'>
            'Has Limited Diplomacy': '[[File:Yes.png|20px|Has Limited Diplomacy]]' if subject_type.has_limited_diplomacy else '[[File:No.png|20px|Not Has Limited Diplomacy]]',  # has_limited_diplomacy: <class 'bool'>
            'Has Overlords Ruler': '[[File:Yes.png|20px|Has Overlords Ruler]]' if subject_type.has_overlords_ruler else '[[File:No.png|20px|Not Has Overlords Ruler]]',  # has_overlords_ruler: <class 'bool'>
            'Institution Spread To Overlord': subject_type.institution_spread_to_overlord.format() if hasattr(subject_type.institution_spread_to_overlord, 'format') else subject_type.institution_spread_to_overlord,  # institution_spread_to_overlord: <class 'eu5.eu5lib.ScriptValue'>
            'Institution Spread To Subject': subject_type.institution_spread_to_subject.format() if hasattr(subject_type.institution_spread_to_subject, 'format') else subject_type.institution_spread_to_subject,  # institution_spread_to_subject: <class 'eu5.eu5lib.ScriptValue'>
            'Is Colonial Subject': '[[File:Yes.png|20px|Is Colonial Subject]]' if subject_type.is_colonial_subject else '[[File:No.png|20px|Not Is Colonial Subject]]',  # is_colonial_subject: <class 'bool'>
            'Join Defensive Wars Always': self.formatter.format_trigger(subject_type.join_defensive_wars_always),  # join_defensive_wars_always: <class 'eu5.trigger.Trigger'>
            'Join Offensive Wars Always': self.formatter.format_trigger(subject_type.join_offensive_wars_always),  # join_offensive_wars_always: <class 'eu5.trigger.Trigger'>
            'Level': subject_type.level,  # level: <class 'int'>
            'Merchants To Overlord Fraction': subject_type.merchants_to_overlord_fraction,  # merchants_to_overlord_fraction: <class 'float'>
            'Minimum Opinion For Offer': subject_type.minimum_opinion_for_offer,  # minimum_opinion_for_offer: <class 'int'>
            'On Disable': self.formatter.format_effect(subject_type.on_disable),  # on_disable: <class 'eu5.effect.Effect'>
            'On Enable': self.formatter.format_effect(subject_type.on_enable),  # on_enable: <class 'eu5.effect.Effect'>
            'Only Overlord Court Language': '[[File:Yes.png|20px|Only Overlord Court Language]]' if subject_type.only_overlord_court_language else '[[File:No.png|20px|Not Only Overlord Court Language]]',  # only_overlord_court_language: <class 'bool'>
            'Only Overlord Culture': '[[File:Yes.png|20px|Only Overlord Culture]]' if subject_type.only_overlord_culture else '[[File:No.png|20px|Not Only Overlord Culture]]',  # only_overlord_culture: <class 'bool'>
            'Only Overlord Or Kindred Culture': '[[File:Yes.png|20px|Only Overlord Or Kindred Culture]]' if subject_type.only_overlord_or_kindred_culture else '[[File:No.png|20px|Not Only Overlord Or Kindred Culture]]',  # only_overlord_or_kindred_culture: <class 'bool'>
            'Overlord Can Cancel': '[[File:Yes.png|20px|Overlord Can Cancel]]' if subject_type.overlord_can_cancel else '[[File:No.png|20px|Not Overlord Can Cancel]]',  # overlord_can_cancel: <class 'bool'>
            'Overlord Can Enforce Peace On Subject': '[[File:Yes.png|20px|Overlord Can Enforce Peace On Subject]]' if subject_type.overlord_can_enforce_peace_on_subject else '[[File:No.png|20px|Not Overlord Can Enforce Peace On Subject]]',  # overlord_can_enforce_peace_on_subject: <class 'bool'>
            'Overlord Inherit If No Heir': '[[File:Yes.png|20px|Overlord Inherit If No Heir]]' if subject_type.overlord_inherit_if_no_heir else '[[File:No.png|20px|Not Overlord Inherit If No Heir]]',  # overlord_inherit_if_no_heir: <class 'bool'>
            'Overlord Modifier': self.format_modifier_section('overlord_modifier', subject_type),  # overlord_modifier: list[eu5.eu5lib.Eu5Modifier]
            'Overlord Share Exploration': '[[File:Yes.png|20px|Overlord Share Exploration]]' if subject_type.overlord_share_exploration else '[[File:No.png|20px|Not Overlord Share Exploration]]',  # overlord_share_exploration: <class 'bool'>
            'Release Country Enabled': self.formatter.format_trigger(subject_type.release_country_enabled),  # release_country_enabled: <class 'eu5.trigger.Trigger'>
            'Strength Vs Overlord': subject_type.strength_vs_overlord,  # strength_vs_overlord: <class 'float'>
            'Subject Can Cancel': '' if subject_type.subject_can_cancel is None else '[[File:Yes.png|20px|Subject Can Cancel]]' if subject_type.subject_can_cancel else '[[File:No.png|20px|Not Subject Can Cancel]]',  # subject_can_cancel: <class 'bool'>
            'Subject Creation Enabled': self.formatter.format_trigger(subject_type.subject_creation_enabled),  # subject_creation_enabled: <class 'eu5.trigger.Trigger'>
            'Subject Modifier': self.format_modifier_section('subject_modifier', subject_type),  # subject_modifier: list[eu5.eu5lib.Eu5Modifier]
            'Subject Pays': subject_type.subject_pays.format(icon_only=True) if hasattr(subject_type.subject_pays, 'format') else subject_type.subject_pays,  # subject_pays: <class 'eu5.eu5lib.Price'>
            'Type': '' if subject_type.type is None else subject_type.type.display_name if subject_type.type else '',  # type: <class 'eu5.eu5lib.Eu5GameConcept'>
            'Use Overlord Laws': '[[File:Yes.png|20px|Use Overlord Laws]]' if subject_type.use_overlord_laws else '[[File:No.png|20px|Not Use Overlord Laws]]',  # use_overlord_laws: <class 'bool'>
            'Use Overlord Map Color': '' if subject_type.use_overlord_map_color is None else '[[File:Yes.png|20px|Use Overlord Map Color]]' if subject_type.use_overlord_map_color else '[[File:No.png|20px|Not Use Overlord Map Color]]',  # use_overlord_map_color: <class 'bool'>
            'Use Overlord Map Name': '[[File:Yes.png|20px|Use Overlord Map Name]]' if subject_type.use_overlord_map_name else '[[File:No.png|20px|Not Use Overlord Map Name]]',  # use_overlord_map_name: <class 'bool'>
            'Visible Through Diplomacy': self.formatter.format_trigger(subject_type.visible_through_diplomacy),  # visible_through_diplomacy: <class 'eu5.trigger.Trigger'>
            'Visible Through Treaty': self.formatter.format_trigger(subject_type.visible_through_treaty),  # visible_through_treaty: <class 'eu5.trigger.Trigger'>
            'War Score Cost': subject_type.war_score_cost,  # war_score_cost: <class 'float'>
        } for subject_type in subject_types]
        return self.make_wiki_table(subject_types_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )
    def generate_traits_table(self):
        result = []
        for sectionname, section in self.get_trait_sections().items():
            result.append('')
            result.append(f'=== {sectionname} ===')
            result.append(self.surround_with_autogenerated_section(sectionname, section, add_version_header=True))
        return result
    def get_trait_sections(self):
        sections = {}
        for category, traits in unsorted_groupby(self.parser.traits.values(),
                                                   key=attrgetter('category')):
            traits = sorted(traits, key=attrgetter('display_name'))
            sections[f'traits_{category}'] = self.get_trait_table(traits)
        return sections

    def get_trait_table(self, traits):
        trait_table_data = [{
            'Name': f'{{{{iconbox|{trait.display_name}|{trait.description}|w=300px|image={trait.get_wiki_filename()}}}}}',
            'Modifier': self.format_modifier_section('modifier', trait),  # modifier: list[eu5.eu5lib.Eu5Modifier]
            'Requirements': self.formatter.format_trigger(trait.allow),  # allow: <class 'eu5.trigger.Trigger'>
            # 'Category': trait.category.display_name if trait.category else '',  # category: <class 'eu5.eu5lib.Eu5GameConcept'>
            'Chance': '' if trait.chance is None else self.create_wiki_list([f'{k}: ...' for k in trait.chance.keys()]) if trait.chance else '',  # chance: <class 'common.paradox_parser.Tree'>
            # 'Flavor': '' if trait.flavor is None else trait.flavor.display_name if trait.flavor else '',  # flavor: <class 'eu5.eu5lib.TraitFlavor'>
        } for trait in traits]
        return self.make_wiki_table(trait_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )
    def generate_unit_types_table(self):
        unit_types = self.parser.unit_types.values()
        unit_types_table_data = [{
            'Name': f' style="background-color: {unit_type.color.get_css_color_string() if unit_type.color else "white"}" | ' + f'{{{{iconbox|{unit_type.display_name}|{unit_type.description}|w=300px|image={unit_type.get_wiki_filename()}}}}}',
            'Age': '' if unit_type.age is None else unit_type.age.get_wiki_link_with_icon() if unit_type.age else '',  # age: <class 'eu5.eu5lib.Age'>
            'Artillery Barrage': unit_type.artillery_barrage,  # artillery_barrage: <class 'int'>
            'Attrition Loss': unit_type.attrition_loss,  # attrition_loss: <class 'float'>
            'Blockade Capacity': unit_type.blockade_capacity,  # blockade_capacity: <class 'float'>
            'Bombard Efficiency': unit_type.bombard_efficiency,  # bombard_efficiency: <class 'float'>
            'Build Time Modifier': unit_type.build_time_modifier,  # build_time_modifier: <class 'float'>
            'Buildable': '' if unit_type.buildable is None else '[[File:Yes.png|20px|Buildable]]' if unit_type.buildable else '[[File:No.png|20px|Not Buildable]]',  # buildable: <class 'bool'>
            'Cannon': '' if unit_type.cannons is None else unit_type.cannons,  # cannons: <class 'int'>
            'Category': unit_type.category.get_wiki_link_with_icon() if unit_type.category else '',  # category: <class 'eu5.eu5lib.UnitCategory'>
            'Combat': '' if unit_type.combat is None else self.create_wiki_list([f'{k}: ...' for k in unit_type.combat.keys()]) if unit_type.combat else '',  # combat: <class 'common.paradox_parser.Tree'>
            'Combat Power': unit_type.combat_power,  # combat_power: <class 'float'>
            'Combat Speed': unit_type.combat_speed,  # combat_speed: <class 'float'>
            'Construction Demand': '' if unit_type.construction_demand is None else unit_type.construction_demand.format(icon_only=True) if hasattr(unit_type.construction_demand, 'format') else unit_type.construction_demand,  # construction_demand: <class 'eu5.eu5lib.GoodsDemand'>
            'Copy From': unit_type.copy_from.get_wiki_link_with_icon() if unit_type.copy_from else '',  # copy_from: <class 'eu5.eu5lib.UnitType'>
            'Country Potential': self.formatter.format_trigger(unit_type.country_potential),  # country_potential: <class 'eu5.trigger.Trigger'>
            'Crew Size': unit_type.crew_size,  # crew_size: <class 'float'>
            'Default': '[[File:Yes.png|20px|Default]]' if unit_type.default else '[[File:No.png|20px|Not Default]]',  # default: <class 'bool'>
            'Flanking Ability': unit_type.flanking_ability,  # flanking_ability: <class 'float'>
            'Food Consumption Per Strength': unit_type.food_consumption_per_strength,  # food_consumption_per_strength: <class 'float'>
            'Food Storage Per Strength': unit_type.food_storage_per_strength,  # food_storage_per_strength: <class 'float'>
            'Frontage': unit_type.frontage,  # frontage: <class 'float'>
            'Gfx Tags': '' if unit_type.gfx_tags is None else unit_type.gfx_tags,  # gfx_tags: typing.Any
            'Hull Size': unit_type.hull_size,  # hull_size: <class 'int'>
            'Impact': '' if unit_type.impact is None else self.create_wiki_list([f'{k}: ...' for k in unit_type.impact.keys()]) if unit_type.impact else '',  # impact: <class 'common.paradox_parser.Tree'>
            'Initiative': unit_type.initiative,  # initiative: <class 'float'>
            'Levy': '[[File:Yes.png|20px|Levy]]' if unit_type.levy else '[[File:No.png|20px|Not Levy]]',  # levy: <class 'bool'>
            'Light': '' if unit_type.light is None else unit_type.light,  # light: typing.Any
            'Limit': '' if unit_type.limit is None else unit_type.limit.format() if hasattr(unit_type.limit, 'format') else unit_type.limit,  # limit: <class 'eu5.eu5lib.ScriptValue'>
            'Location Potential': self.formatter.format_trigger(unit_type.location_potential),  # location_potential: <class 'eu5.trigger.Trigger'>
            'Location Trigger': self.formatter.format_trigger(unit_type.location_trigger),  # location_trigger: <class 'eu5.trigger.Trigger'>
            'Maintenance Demand': '' if unit_type.maintenance_demand is None else unit_type.maintenance_demand.format(icon_only=True) if hasattr(unit_type.maintenance_demand, 'format') else unit_type.maintenance_demand,  # maintenance_demand: <class 'eu5.eu5lib.GoodsDemand'>
            'Maritime Presence': '' if unit_type.maritime_presence is None else unit_type.maritime_presence.format() if hasattr(unit_type.maritime_presence, 'format') else unit_type.maritime_presence,  # maritime_presence: <class 'eu5.eu5lib.ScriptValue'>
            'Max Strength': unit_type.max_strength,  # max_strength: <class 'float'>
            'Mercenaries Per Location': self.create_wiki_list([f'{self.formatter.format_percent(factor)} {pop_type.get_wiki_icon()}' for m in unit_type.mercenaries_per_location for pop_type, factor in m.items()]),
            'Morale Damage Done': unit_type.morale_damage_done,  # morale_damage_done: <class 'float'>
            'Morale Damage Taken': unit_type.morale_damage_taken,  # morale_damage_taken: <class 'float'>
            'Movement Speed': unit_type.movement_speed,  # movement_speed: <class 'float'>
            'Strength Damage Done': unit_type.strength_damage_done,  # strength_damage_done: <class 'float'>
            'Strength Damage Taken': '' if unit_type.strength_damage_taken is None else unit_type.strength_damage_taken,  # strength_damage_taken: typing.Any
            'Supply Weight': unit_type.supply_weight,  # supply_weight: <class 'float'>
            'Transport Capacity': unit_type.transport_capacity,  # transport_capacity: <class 'float'>
            'Upgrades To': '' if unit_type.upgrades_to is None else unit_type.upgrades_to,  # upgrades_to: typing.Any
            'Upgrades To Only': unit_type.upgrades_to_only.get_wiki_link_with_icon() if unit_type.upgrades_to_only else '',  # upgrades_to_only: <class 'eu5.eu5lib.UnitType'>
            'Use Ship Names': '' if unit_type.use_ship_names is None else '[[File:Yes.png|20px|Use Ship Names]]' if unit_type.use_ship_names else '[[File:No.png|20px|Not Use Ship Names]]',  # use_ship_names: <class 'bool'>
        } for unit_type in unit_types]
        return self.make_wiki_table(unit_types_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )
    def generate_wargoals_table(self):
        wargoals = self.parser.wargoals.values()
        wargoals_table_data = [{
            'Name': f'{{{{iconbox|{wargoal.display_name}|{wargoal.description}|w=300px|image={wargoal.get_wiki_filename()}}}}}',
            'Attacker': '' if wargoal.attacker is None else self.create_wiki_list([f'{k}: ...' for k in wargoal.attacker.keys()]) if wargoal.attacker else '',  # attacker: <class 'common.paradox_parser.Tree'>
            'Defender': '' if wargoal.defender is None else self.create_wiki_list([f'{k}: ...' for k in wargoal.defender.keys()]) if isinstance(wargoal.defender, Tree) else "''Unknown type''" if wargoal.defender else '',  # defender: <class 'common.paradox_parser.Tree'>
            'Ticking War Score': wargoal.ticking_war_score,  # ticking_war_score: <class 'float'>
            'Type': wargoal.type,  # type: <class 'str'>
            'War Name': wargoal.war_name,  # war_name: <class 'str'>
            'War Name Is Country Order Agnostic': '[[File:Yes.png|20px|War Name Is Country Order Agnostic]]' if wargoal.war_name_is_country_order_agnostic else '[[File:No.png|20px|Not War Name Is Country Order Agnostic]]',  # war_name_is_country_order_agnostic: <class 'bool'>
        } for wargoal in wargoals]
        return self.make_wiki_table(wargoals_table_data, table_classes=['mildtable', 'plainlist'],
                                        one_line_per_cell=True,
                                        remove_empty_columns=True,
                                        )


if __name__ == '__main__':
    TableGenerator().run(sys.argv)