"""
Generates script_docs_data.py from the output of the console command script_docs

Per default, the script docs are expected to be in the "docs" subfolder of the EU5DIR_DOCUMENTS
from localsettings. A different folder can be provided as a command line argument
"""
import re
from argparse import ArgumentParser
from pathlib import Path

import sys

from PyHelpersForPDXWikis.localsettings import EU5DIR_DOCUMENTS


class ScriptDocsReader:

    def __init__(self, folder: Path):
        self.folder = folder


    def generate_new_script_docs_data_contents(self):
        output = [
            '# generated by:',
            '# eu5/script_docs_helper.py',
            '',
            '### Triggers ###',
            self.get_trigger_output(),
            '### Effects ###',
            self.get_effects_output(),
            '### Event targets ###',
            self.get_event_targets_output(),
        ]
        return '\n'.join(output)

    def get_trigger_output(self):
        trigger_keywords = self.read_file('triggers.log')
        output = f'triggers_from_script_docs = {{\'{"', '".join(trigger_keywords)}\'}}'
        return output

    def get_effects_output(self):
        effect_keywords = self.read_file('effects.log')
        output = f'effects_from_script_docs = {{\'{"', '".join(effect_keywords)}\'}}'
        return output

    def get_event_targets_output(self):
        effect_keywords = self.read_file('event_targets.log', '###')
        output = f'event_targets_from_script_docs = {{\'{"', '".join(effect_keywords)}\'}}'
        return output

    def write_script_docs(self):
        output = self.generate_new_script_docs_data_contents()

        with open(Path(__file__).parent / 'script_docs_data.py', 'w') as py_file:
            print(f'Updating script_docs_data.py...')
            print(output)
            py_file.write(output)

    def read_file(self, script_docs_filename: str, line_prefix = '##'):
        with open(self.folder / script_docs_filename) as script_docs_file:
            contents = script_docs_file.read()
            keywords = []
            for match in re.finditer('^' + line_prefix + r' (\S*)(.*)$', contents, re.MULTILINE):
                keyword = match.group(1)
                extra_text = match.group(2)
                if extra_text:
                    raise Exception(f'Unexpected extra text "{extra_text}" after keyword "{keyword}"')
                keywords.append(keyword)
        return keywords


if __name__ == '__main__':
    parser = ArgumentParser(
        description='Generates script_docs_data.py from the output of the console command script_docs')
    parser.add_argument('folder',
                        type=Path,
                        nargs='?',
                        default=EU5DIR_DOCUMENTS / 'docs',
                        help='folder which contains the output of script_docs. The default is the "docs" subfolder of EU5DIR_DOCUMENTS from localsettings (%(default)s)',
                        )
    args = parser.parse_args()
    ScriptDocsReader(args.folder).write_script_docs()
