from functools import cached_property
from pathlib import Path

from common.paradox_lib import Game


class SurvivingMarsRelaunched(Game):
    """Never construct this object manually. Use the variable survivingmarsrelaunchedgame instead.
    This way all data can be cached without having to pass on references to the game or the parser"""
    name = 'Surviving Mars: Relaunched'
    short_game_name = 'smr'
    wiki_domain = 'survivingmars.paradoxwikis.com'

    unpacked_path: Path = None

    @cached_property
    def parser(self):
        """returns the shared SMRParser"""

        # the import has to be inside this method to allow indirect circular dependencies if an entity which is
        # generated by the parser needs to call a method from the parser
        from smr.parser import SMRParser
        return SMRParser(self.unpacked_path)

    @cached_property
    def version(self):
        return '.'.join(self.full_version.split('.')[0:3])

    @cached_property
    def full_version(self):
        return self.parser.full_version


survivingmarsrelaunchedgame = SurvivingMarsRelaunched()