import hashlib
import re
from functools import cached_property
from pathlib import Path
from typing import Any

from PIL import Image

from common.paradox_lib import IconEntity
from common.paradox_parser import Tree
from common.wiki import WikiTextFormatter
from smr.game import survivingmarsrelaunchedgame


class SMRAdvancedEntity(IconEntity):
    def __init__(self, name: str, display_name: str = '', **kwargs):
        display_name = display_name.replace('"', '')
        super().__init__(name, display_name, **kwargs)

    @cached_property
    def _image_reference(self) -> Image.Image | None:
        if self.icon:
            icon_file = (survivingmarsrelaunchedgame.unpacked_path / self.icon).with_suffix('.dds')
            if not icon_file.exists():
                for file in survivingmarsrelaunchedgame.unpacked_path.glob(f'DLC/*/{Path(self.icon).with_suffix(".dds")}'):
                    icon_file = file
            if icon_file.exists():
                return Image.open(icon_file)
            else:
                return None
        else:
            return None

    @cached_property
    def _image_reference_left_img(self) -> Image.Image | None:
        full_image = self._image_reference
        if full_image:
            left_img = full_image.crop((0, 0, full_image.size[0] / 2, full_image.size[1]))
            return left_img
        else:
            return None

    def get_image_reference(self) -> Image.Image | None:
        return self._image_reference

    def get_image_data_hash(self) -> str | None:
        reference = self.get_image_reference()
        if reference is None:
            return None
        return hashlib.sha256(reference.tobytes()).hexdigest()


class Building(SMRAdvancedEntity):
    # just a few attributes autogenerated with the helper
    # there are much more, but most of them are very specific
    # this would need grouping of attributes
    __generated_by_class: str
    __parents: Tree
    build_category: str
    build_points: int = None
    build_pos: int = None
    can_refab: bool = True
    construction_cost_Concrete: int = 0
    construction_cost_Electronics: int = 0
    construction_cost_Metals: int = 0
    demolish_debris: int = None
    demolish_sinking: Tree = None
    description: str = ''
    # use icon instead
    # display_icon: str = ''
    display_name: str = ''
    display_name_pl: str
    display_name_twolines: str
    dome_forbidden: bool = False
    dome_required: bool = False
    electricity_consumption: int = None
    encyclopedia_id: str = ''
    encyclopedia_image: str = ''
    entity: str = ''
    is_tall: bool = False
    label1: str = ''
    label2: str = ''
    maintenance_resource_amount: int = 0
    maintenance_resource_type: str = ''
    object_class: Any # possible types(out of 270): <class 'str'>(269), <class 'bool'>(1)
    palette_color1: str = ''
    palette_color2: str = ''
    palette_color3: str = ''
    persist_baseclass: str
    prio_button: bool = True
    upgrade1_description: str = ''
    upgrade1_display_name: str = ''
    upgrade1_icon: str = ''
    upgrade1_id: str = ''
    upgrade1_mod_prop_id_1: str = ''
    upgrade2_description: str = ''
    upgrade2_display_name: str = ''
    upgrade2_icon: str = ''
    upgrade2_id: str = ''
    upgrade2_mod_prop_id_1: str = ''
    upgrade3_description: str = ''
    upgrade3_display_name: str = ''
    upgrade3_icon: str = ''
    upgrade3_id: str = ''
    upgrade3_mod_prop_id_1: str = ''

    def get_image_reference(self) -> Image.Image | None:
        return self._image_reference_left_img

    def get_wiki_filename(self) -> str:
        if not self.icon:
            return ''
        prefix = f'Building '
        icon_overrides = {
            'DomeOval': 'oval dome',
            'DomeMedium': 'medium dome',
        }
        if self.name in icon_overrides:
            icon_name = icon_overrides[self.name]
        else:
            icon_name = Path(self.icon.lower()).stem
        return f'{prefix}{icon_name}.png'

    def get_obsolete_wiki_filenames(self) -> list[str]:
        obsolete_names = []
        for basename in (self.display_name, Path(self.icon).stem):
            for prefix in ('Building ', 'Building-', 'Building - ', ''):
                obsolete_names.append(f'{prefix}{basename}.png')
        # obsolete_names.append(self.display_name + '.png')
        for other_name in ['Building - Mirror Sphere.png' , 'Cave of Wonders.png']:
            if other_name in obsolete_names:
                obsolete_names.remove(other_name)

        return obsolete_names

    # def get_alternative_wiki_filenames(self) -> list[str]:
    #     return [self.display_name + '.png']

    def get_wiki_file_description(self) -> str:
        if self.display_name:
            fpk, _, file = self.icon.partition('/')
            file = Path(file).with_suffix('.dds')
            return  f'"Surviving Mars: Relaunched" icon for {self.get_class_name_as_wiki_page_title().lower()} [[{self.display_name}]]\n\nSource: <code>{file}</code> in <code>{fpk}.fpk</code>'
        else:
            return ''

    @cached_property
    def upgrades(self) -> list[BuildingUpgrade]:
        upgrades = []
        for i in range(1, 4):
            upgrade_name = getattr(self, f'upgrade{i}_id')
            if upgrade_name:
                display_name = getattr(self, f'upgrade{i}_display_name')
                description = getattr(self, f'upgrade{i}_description')
                icon = getattr(self, f'upgrade{i}_icon')
                upgrades.append(BuildingUpgrade(
                    upgrade_name,
                    display_name,
                    description=description,
                    icon=re.sub(r'0[1-3](\.(png|tga))?$', '01.png', icon),
                    building=self
                ))
                upgrades.append(BuildingUpgrade(
                    upgrade_name,
                    display_name,
                    description=description,
                    icon=re.sub(r'0[1-3](\.(png|tga))?$', '02.png', icon),
                    building=self
                ))
                upgrades.append(BuildingUpgrade(
                    upgrade_name,
                    display_name,
                    description=description,
                    icon=re.sub(r'0[1-3](\.(png|tga))?$', '03.png', icon),
                    building=self
                ))

        return upgrades


class BuildingUpgrade(SMRAdvancedEntity):
    """unfinished. only used to store images"""

    building: Building

    def get_wiki_filename_prefix(self):
        return 'Upgrade'

    def get_obsolete_wiki_filenames(self) -> list[str]:
        if self.get_wiki_filename().endswith('_01.png'):
            return [self.get_wiki_filename().removesuffix('_01.png').removeprefix('Upgrade ') + '.png']
        else:
            return []

    def get_wiki_file_description(self) -> str:
        if self.display_name:
            fpk, _, file = self.icon.partition('/')
            file = Path(file).with_suffix('.dds')
            return  f'Source: <code>{file}</code> in <code>{fpk}.fpk</code>\n\n"Surviving Mars: Relaunched" icon for {self.get_class_name_as_wiki_page_title().lower()} {self.display_name} for building(s):\n* [[{self.building}]]'
        else:
            return ''

class Crop(SMRAdvancedEntity):
    DisplayNamePlural: str = ''
    FarmClass: str
    FoodOutput: int
    GrowthSequence: str = ''
    GrowthTime: int = 0
    InitialGrowthSequence: str = ''
    InitialGrowthTime: int = 0
    Locked: bool = False
    OxygenProduction: int = 0
    ResourceType: str = ''
    SoilEffect: int = 0
    SortKey: int
    WaterDemand: int = 0
    group: str

    def get_image_reference(self) -> Image.Image | None:
        return self._image_reference_left_img

    def get_wiki_file_description(self) -> str:
        fpk, _, file = self.icon.partition('/')
        file = Path(file).with_suffix('.dds')
        return  f'"Surviving Mars: Relaunched" icon for crop [[Food#{self.display_name}|{self.display_name}]]\n\nSource: <code>{file}</code> in <code>{fpk}.fpk</code>'

class Law(SMRAdvancedEntity):
    DisableConditions: Tree = None
    PolicyCategory: str = ''
    PreIndependence: bool = False
    PrepareOnGameStart: bool = False
    SingleLaw: bool = False
    SortKey: int = 0
    can_be_repealed: bool = True
    description: str
    group: str
    icon: str = 'UI/IconsRemaster/Laws/automation_3.png'

    def __init__(self, name: str, display_name: str = '', **kwargs):
        if 'icon' in kwargs:
            kwargs['icon'] = kwargs['icon'].replace('_1.', '_3.')
        super().__init__(name, display_name, **kwargs)

    def get_wiki_filename(self) -> str:
        return f'Law {Path(self.icon.lower()).stem.removesuffix("_3")}.png'

    def get_wiki_file_description(self) -> str:
        fpk, _, file = self.icon.partition('/')
        file = Path(file).with_suffix('.dds')
        return  f'"Surviving Mars: Relaunched" icon for law [[Laws#{self.display_name}|{self.display_name}]]\n\nSource: <code>{file}</code> in <code>{fpk}.fpk</code>'

class Technology(SMRAdvancedEntity):
    Comment: str = ''
    Effect_Code: Tree = None
    Effect_Funding: Tree = None
    Effect_GrantApplicants: Tree = None
    Effect_ModifyConstructionCost: list[Tree] = []
    Effect_ModifyLabel: Any = None # possible types(out of 73): <class 'common.paradox_parser.Tree'>(43), list[common.paradox_parser.Tree](30)
    Effect_ModifyResupplyParam: list[Tree] = []
    Effect_ModifyUpgrade: list[Tree] = []
    Effect_TechBoost: Tree = None
    Effect_TechEnableBuildingInEnvironment: list[Tree] = []
    Effect_TechUnlockBuilding: Any = None # possible types(out of 75): <class 'common.paradox_parser.Tree'>(58), list[common.paradox_parser.Tree](17)
    Effect_UnlockDeeperDeposits: Tree = None
    Effect_UnlockResupplyItem: Any = None
    Effect_UnlockSpecialProject: Any = None
    Effect_UnlockTrait: Tree = None
    Effect_UnlockUpgrade: Any = None
    #OnResearched: Function = None
    SortKey: int = 0
    #condition: Function = None
    cost_increase: int = 0
    description: str
    # display_name: str
    group: str
    # icon: str
    # id: str
    mystery: str = ''
    param1: int = 0
    param1comment: str = ''
    param2: int = 0
    param2comment: str = ''
    param3: int = 0
    param3comment: str = ''
    position: Tree = None
    repeatable: bool = False
    short_description: str = ''

    def get_wiki_filename(self) -> str:
        return f'Technology - {self.display_name}.png'

    def get_wiki_file_description(self) -> str:
        fpk, _, file = self.icon.partition('/')
        file = Path(file).with_suffix('.dds')
        return  f'"Surviving Mars: Relaunched" technology icon\n\nSource: <code>{file}</code> in <code>{fpk}.fpk</code>'

    def get_obsolete_wiki_filenames(self) -> list[str]:
        obsolete_names = []
        for basename in (self.display_name, Path(self.icon).stem):
            for prefix in ('Technology ', 'Technology-', 'Technology- ', 'Technology -', 'Technology - ', ''):
                obsolete_names.append(f'{prefix}{basename}.png')
        for other_name in ['Magnetic extraction.png', 'Technology - Resilience.png']:
            if other_name in obsolete_names:
                obsolete_names.remove(other_name)
        return obsolete_names

class Unit(Building):

    def get_wiki_filename(self) -> str:
        if not self.icon or not self.display_name:
            return ''
        return WikiTextFormatter.normalize_page_title(f'{self.display_name}.png'.lower())

    def get_obsolete_wiki_filenames(self) -> list[str]:
        obsolete_names = super().get_obsolete_wiki_filenames() + [super().get_wiki_filename()]

        for other_name in ['Shuttle.png', 'Drone.png']:
            if other_name in obsolete_names:
                obsolete_names.remove(other_name)

        return obsolete_names
