from functools import cached_property

from PyHelpersForPDXWikis.localsettings import AOW4DIR
from common.paradox_lib import Game


class AgeOfWonders4(Game):
    """Never construct this object manually. Use the variable aow4game instead.
    This way all data can be cached without having to pass on references to the game or the parser"""
    name = 'Age of Wonders 4'
    short_game_name = 'aow4'
    game_path = AOW4DIR
    launcher_settings = game_path / 'launcher-settings.json'
    wiki_domain = 'aow4.paradoxwikis.com'

    @cached_property
    def parser(self):
        """returns the shared AoW4Parser"""

        # the import has to be inside this method to allow indirect circular dependencies if an entity which is
        # generated by the parser needs to call a method from the parser
        from aow4.parser import AoW4Parser
        return AoW4Parser()

    @cached_property
    def version(self):
        return 'pre-release'

    @cached_property
    def full_version(self):
        return 'pre-release'


aow4game = AgeOfWonders4()
